### ISSUE TITLE
Update the repo to RC

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/ng-formly#166]
When would be the best time to upgrade the repo to Release Candidate.

And also should we be following semver similar to angular team, and would that mean the Final release version would be 2.0.0 or 1.0.0?

**Comment by aitboudad** [comment]
> When would be the best time to upgrade the repo to Release Candidate.

I think we have done the most important things, we should wait one or two weeks before RC

> And also should we be following semver similar to angular team, and would that mean the Final release version would be 2.0.0 or 1.0.0?

`1.0.0` is my preference :)

**Comment by mohammedzamakhan** [comment]
1.0.0 is my preference too, but before that we have to make sure that ui-bootstrap is not in this repo, but in its own repo.

**Comment by mohammedzamakhan** [comment]
Somehow I also want to rename the repo to ng-formly, instead of ng2-formly.

**Comment by thiagogjt** [comment]
I think it is a good idea to group the dependencies after the ui modules have its own repositories
Like:
@ng-formly/core
@ng-formly/ui-bootstrap
@ng-formly/ui-material
...

**Comment by mohammedzamakhan** [comment]
@thiagogjt It would cost $14/month to get those @ng-formly on npmjs.com

it would be free for us to have

ng-formly
ng-formly-ui-bootstrap
ng-formly-ui-material
...

**Comment by thiagogjt** [comment]
@mohammedzamakhan I did not know that there were costs involved in grouping the packages.

**Comment by mohammedzamakhan** [comment]
Should we upgrade to rc after the fix of #270 and #230?

**Comment by mohammedzamakhan** [comment]
https://twitter.com/IgorMinar/status/807564558986514432?ref_src=twsrc%5Etfw
@IgorMinar
