### ISSUE TITLE
Sample for loading form layout from service

### ISSUE THREAD

**Issue by Stwissel** [formly-js/ng-formly#362]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] clarification request
```

**Current behavior**

Not started yet - just want to know

**Expected behavior**

Can I load a form definition dynamically. E.g. by calling a service that loads JSON from URL with parameters.
If yes: I'll try and commit sample back.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mohammedzamakhan** [comment]
Yes you should be able to do that

**Comment by aitboudad** [comment]
but it should be optional, as we won't want to add an additional deps (`@angular/http`) to our package.
Isn't enough to add just an example into the doc ?

**Comment by franzeal** [comment]
I'm doing this in the application I work on, so it's certainly possible.

**Comment by Stwissel** [comment]
Awesome. I had a working example with formly for Angular 1.x where an admin could store form definitions in a NoSQL (Mongo, Couch) to accommodate different form needs. 
So I'll port this to Angular2 and report back

**Comment by mohammedzamakhan** [comment]
any updates @Stwissel ?

**Comment by franzeal** [comment]
How's this?
https://plnkr.co/edit/wsLuTUiw5Xf8O3LygBhg?p=preview

**Comment by aitboudad** [comment]
we can use https://github.com/angular/in-memory-web-api to simulate an HTTP request
