### ISSUE TITLE
Problem adding a new property inside field

### ISSUE THREAD

**Issue by Gaedr** [formly-js/ng-formly#365]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
I'm trying to extend the select input field to use multiple selected option in a bootstrap way including a property `multiple` inside in `select` tag.
[Bootstrap Forms](http://getbootstrap.com/css/#forms-controls)

For that purpose I'm now creating a custom type `multiselect` in a similar way the  *hello.ts+ example file:
``` typescript
FormlyModule.forRoot({
      types: [
        {
          name: 'multiselect',
          extends: 'select',
          defaultOptions: {
            templateOptions: {
              multiple: 'multiple'
            }
          }
        }
      ]
})
```
Reading the code of ng2-formly I can understand you can add your own properties in the template adding a new property inside the _templateOptions_, but the property `multiple` not appear in all.

What is the correct way to add that property?

**Please tell us about your environment:**

- Angular2 version: 2.2.3

**Comment by franzeal** [comment]
You always have the option to create your own field types that looks and behaves exactly how you need it to.  The demo (https://github.com/formly-js/ng-formly/blob/master/demo/toggle.ts) and ui-bootstrap (https://github.com/formly-js/ng-formly/blob/master/src/ui-bootstrap/types/select.ts) module are good examples that show how to do this.
