### ISSUE TITLE
Advanced Layout : Display a field value in a html section set inside the FormlyFieldConfig Array

### ISSUE THREAD

**Issue by ampsarfraz** [formly-js/ng-formly#374]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```
How to display the value of a field in a html template provided inside the FormlyFieldConfig Array?

For example , In the advanced Layout template , I have added the below section in the array to display the value of otherInput field, but it doesn't work. Can you please help me to make it work?
```
{
        template: '<h4>test {{model.otherInput}}</h4>'
 }
```

Plunker

https://plnkr.co/edit/ZFgRjuSfyDjNPo6vguBF?p=preview

**Comment by aitboudad** [comment]
template support only plain string values (angular doesn't allow that), to handle you use case just use a custom wrapper
Ex: https://github.com/formly-js/ng-formly/blob/master/src/ui-bootstrap/wrappers/description.ts

**Comment by franzeal** [comment]
Here's a plunker demonstrating how I approach reproducing this capability that angular-formly had:
https://plnkr.co/edit/AISe9Np6QA2CnqdOrMqq?p=preview

**Comment by Almar** [comment]
Would this solution work with aot?

**Comment by franzeal** [comment]
It should.  My expectation would be that some components may need to be exposed as [entryComponents](https://angular.io/docs/ts/latest/api/core/index/NgModule-interface.html#!#entryComponents-anchor).

A colleague of mine is setting up the build process which includes aot and I believe he's well past that point.  I have no visibility to that work to verify and know the details, but will at some point.

**Comment by franzeal** [comment]
I figured I'd pass these along as they're related.  Hopefully we'll work through this, but I've not had the opportunity to do so personally.

Angular 2:
http://stackoverflow.com/a/41460129/4236606
https://github.com/angular/angular/issues/11780

http://blog.assaf.co/angular-2-harmony-aot-compilation-with-lazy-jit-2/
https://github.com/shlomiassaf/lazy-jit

Angular 4:
https://github.com/angular/angular/issues/15510

**Comment by franzeal** [comment]
Following up again.  I can confirm that this will work just fine in an AOT application.  The important thing to realize is these dynamic templates do require the JIT compiler, so for in AOT it must be provided (see the above links).  We ended up providing our own ResourceLoader as well, though that may have been more a result of using Rollup.
