### ISSUE TITLE
tslint failed on "no-access-missing-member"

### ISSUE THREAD

**Issue by Knoxvillekm** [formly-js/ng-formly#379]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
In component's template tslinf failed on "no-access-missing-member":
```
The property "valid" that you're trying to access does not exist in the class declaration.
The property "formControl" that you're trying to access does not exist in the class declaration.
The property "field" that you're trying to access does not exist in the class declaration.
The property "to" that you're trying to access does not exist in the class declaration.
```
Component extends FieldType. This property has only getter in declared class.

**Please tell us about your environment:**

* **awesome-typescript-loader:** 3.0.4 
* **codelyzer:** 2.0.0 
* **tslint:** 4.4.2

**Comment by aitboudad** [comment]
related https://github.com/mgechev/codelyzer/issues/191, you need to disable the rule `no-access-missing-member` until `codelyzer` provide a support for extended classes
