### ISSUE TITLE
FormControl for Hidden Fields not loaded in form.controls - Angular 4

### ISSUE THREAD

**Issue by mnaveenriaz** [formly-js/ng-formly#391]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
I have a ng2 form with a few hidden fields and a few visible fields. In the field definitions, there is no connection between hidden and visible fields except thru lifecycle events. 
```
this.form.controls[fieldArray[0]].valueChanges.subscribe((updatedValue: any) => {
   var modelValues = [];
   if (updatedValue) {
     modelValues.push(updatedValue);
     this.setValues(functionCall, modelValues, setFieldName);
   }
}));
```

When user updates a visible field, the hidden field value are set using 
```
   this.form.controls[setFieldName].setValue(valueStr);
```

But after upgrading to Angular 4, the formControls for the hidden fields are not loaded. So the valueChanges function errors out with one of the below messages
```
Cannot read property 'valueChanges' of null
Cannot read property 'valueChanges' of undefined
Cannot read property 'setValue' of null
Cannot read property 'setValue' of undefined
```
Need help in loading all the controls required by the form irrespective of hidden property.

**Expected behavior**
Working without issues in Angular 2.*

**Code Versions**
```
    "@angular/common": "4.0.0-rc.2",
    "@angular/compiler": "4.0.0-rc.2",
    "@angular/core": "4.0.0-rc.2",
    "@angular/forms": "4.0.0-rc.2",
    "@angular/http": "4.0.0-rc.2",
    "@angular/platform-browser": "4.0.0-rc.2",
    "@angular/platform-browser-dynamic": "4.0.0-rc.2",
    "@angular/router": "4.0.0-rc.2",
    "ng-formly": "github:formly-js/ng-formly",
```

**Comment by aitboudad** [comment]
can you provide a plunkr or a repo reproducing the issue?

**Comment by davidoween** [comment]
It happens the same to me

https://stackblitz.com/edit/angular-xfgnyt?file=app%2Fapp.component.ts,app%2Fapp.component.html

:)

**Comment by aitboudad** [comment]
The provided example use an old version of Formly which is not supported anymore, please check against latest version instead.

**Comment by davidoween** [comment]
I use version 5.x.x

**Comment by aitboudad** [comment]
Ok, just to clarify that's an expected behavior when a field is hidden we remove the formControl from the parent form. In case you want to access to the field form control of the field use `field.formControl`.
In `v6` you can get access from the parent field as well: `parentField.get('fieldName').formControl`
