### ISSUE TITLE
Share values of inputs between multiple ones

### ISSUE THREAD

**Issue by Callehabana** [formly-js/ng-formly#394]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

I have a fom and I would like one of my input take the value calculated with values from two others. On this plunker, you have an example of what I would do : An Input that gets the values of the last and first name to make a full one.
I took example/forked of your plunker about defaut values :
https://plnkr.co/edit/x0Ri0Od5f2Q7DiwueaCD?p=preview

I don't know how to bind it to the model thanks to the "userFields" configuration.

Thanks in advance

**Comment by mohammedzamakhan** [comment]
Working example https://plnkr.co/edit/uxiTED5kp0j07iYpsduc
