### ISSUE TITLE
FormArray validation

### ISSUE THREAD

**Issue by Knoxvillekm** [formly-js/ng-formly#396]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

How to best validate all controls in FormArray?

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/5fnx4MxHFQpqncG7Jcm5?p=preview

**Comment by aitboudad** [comment]
What is your use case?
you can add your custom validation in the `fieldArray`:
```ts
fieldArray: {
   validators: { ... },
   ...
}
```
