### ISSUE TITLE
Angular 4 compatibility

### ISSUE THREAD

**Issue by jacobharasimo** [formly-js/ng-formly#399]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

Angular 4 compatibility

**Expected behavior**

`<template>` element is deprecated. Use `<ng-template>` instead

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Providing support and functionality for new version of angular.

**Please tell us about your environment:**

Windows system

* **Angular version:** 2.0.X

Angular 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

* **Node (for AoT issues):** `node --version` =   
LTE

**Comment by aitboudad** [comment]
The latest version of `ng-formly: 1.0.0-rc.2` is fully compatible with ng 4, can you check which version of `ng-formly` you use?

**Comment by jacobharasimo** [comment]
I was using "ng2-formly": "2.0.0-beta.14" as that seamed to be the newist published release
