### ISSUE TITLE
Multiple Checkbox example

### ISSUE THREAD

**Issue by b4z81** [formly-js/ng-formly#400]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I can't use multiple checkbox inputs.

**Expected behavior**

Could someone post an example of multiple checkbox?

**Comment by franzeal** [comment]
As used in the [demo](https://github.com/formly-js/ng-formly/blob/master/demo/hello.ts):

```ts
{
    key: 'interest',
    type: 'multicheckbox',
    templateOptions: {
        label: 'Interest',
        options: [
            {
                key: 'sports',
                value: 'Sports'
            },
            {
                key: 'movies',
                value: 'Movies'
            },
            {
                key: 'others',
                value: 'Others'
            }
        ]
    }
}
`

**Comment by werts** [comment]
@franzeal can options get from server? i suffered  'RROR Error: Cannot find control with unspecified name attribute'

**Comment by franzeal** [comment]
Options can come from a server, but you'll probably still want to provide an empty options array (unless it's been updated recently, I believe the type assumes the templateOptions.options is not undefined).

Use the lifecycle hooks to update the templateOptions.options with a new array instance that you get from some asynchronous service call.

**Comment by werts** [comment]
#516 can be related,i think there might be lost a 'name' attribute.but i'm not sure.thanks for your reply.but i still cannot solve it, and i cant set up a  plunker, problems occured from server.
some error here：ERROR Error: Cannot find control with unspecified name attribute。
and the error line show in multicheckbox template.
<input type="checkbox" [value]="option.value" [formControl]="formControl.get(option.key)"
        [formlyAttributes]="field" class="custom-control-input">
