### ISSUE TITLE
Formly duplicates provided classNames

### ISSUE THREAD

**Issue by stephanjust** [formly-js/ng-formly#404]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
In nested forms formly duplicates classNames by applying them to the formly-field and the inner formly-form (the container for the inner field).

Our JSON roughly looks like: 
```
"fields": [
{
    "className": "row",
    "fieldGroup": [
    {
        ...
        "className": "col-xs-2"
    },
    {
        ...
        "className": "col-xs-10"
    }
]
```
and Formly generates the following HTML:
```
<formly-form>
    <formly-field class="row">
        <formly-group>
            <formly-form class="row">
                <formly-field class="col-xs-2">
                ... 
                </formly-field>
                <formly-field class="col-xs-10">
                </formly-field>
            </formly-form>
        </formly-group>
    </formly-field>
</formly-form>
```
**Expected behavior**
The className of the fieldGroup should only be applied once. This worked fine with angular@2.4.9 and ng2-formly@2.0.0-beta.14.

* **Angular version:** 4.0.1
* **Formly version:** 1.0.0-rc.2

* **Browser:** all

* **Language:** all

**Comment by batonmedia** [comment]
Please update npm package.

**Comment by aitboudad** [comment]
a new version is published now, please check it!

**Comment by aitboudad** [comment]
I decided to keep the className for `FormlyForm` even if `fieldGroup` is present this will introduce a BC break but we don't have a choice:

- when using `className` it should refer to the root element `<formly-field>`
- in order to apply className for  `<formly-form>` when using `fieldGroup` you should define the class name in `fieldGroupClassName` option.

### Before
```ts
  className: 'row',
  fieldGroup: ...
```

### After
```ts
  fieldGroupClassName: 'row',
  fieldGroup: ...
```
