### ISSUE TITLE
Forms do not render, console says "TypeError: Cannot read property 'templateOptions' of undefined"

### ISSUE THREAD

**Issue by rjsteinert** [formly-js/ng-formly#411]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Install ng-cli, generate a new app, start the app, follow the instructions for the hello world in the README, see lots of errors in the console.

<img width="715" alt="screen shot 2017-05-03 at 6 34 09 am" src="https://cloud.githubusercontent.com/assets/156575/25647521/56757a44-2fcb-11e7-9863-01da18dc20b0.png">

**Expected behavior**

I expected to see a working form but instead I see a lot of errors. 

**Minimal reproduction of the problem with instructions**

```
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest
ng new ng-formly-hello-world
cd ng-formly-hello-world
npm install --save ng-formly
npm start
```
Then make the [changes I made in this commit](https://github.com/rjsteinert/ng-formly-hello-world/commit/9a84729a02601f09f9444d37234148a9d7a327b5) that follow the README's instructions.

**What is the motivation / use case for changing the behavior?**

I would like to use this library for generating forms based on JSON.

**Please tell us about your environment:**

Mac OS 10.12.3, VS Code, npm v4.2.0,  node v7.8.0, @angular-cli v1.0.1

* **Angular version:** 2.0.X

Angular v4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 58.0.3029.81 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript v2.2.0

* **Node (for AoT issues):** `node --version` =
node v7.8.0

**Comment by franzeal** [comment]
Should already be fixed, see https://github.com/formly-js/ng-formly/pull/383

It hasn't made a release, but you could reference that or a later commit in the meantime.

**Comment by aitboudad** [comment]
@rjsteinert see https://github.com/rjsteinert/ng-formly-hello-world/pull/1

**Comment by rjsteinert** [comment]
@aitboudad @franzeal So awesome! Works now. Thank you for the support. We might use ng-formly for our rewrite of the Open Source survey software Tangerine which has been used by over 30 organizations to conduct over 1 million assessments and surveys in over 50 countries and in 100 languages. https://github.com/Tangerine-Community/Tangerine
