### ISSUE TITLE
How to determine if there is error in the form?

### ISSUE THREAD

**Issue by laterbreh** [formly-js/ng-formly#413]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```
I have followed the readme here on github and have my form working. All I am trying to do is disable the submit button when there is an error on the form. What would be the variable I can test to determine if the form contains an error so I can disable the submit button?

I have tried {{form | json}} to view its properties and none of them change to indicate there is an error, and it still maintains that the form is pristine even when it is not. 

What am I doing wrong here?
```
form: FormGroup = new FormGroup({});
 userFields: FormlyFieldConfig = [{
    className: 'row',
    fieldGroup: [{
      className: 'col-md-12',
      key: 'email',
      type: 'input',
      templateOptions: {
        type: 'email',
        label: 'Email address',
        placeholder: 'Enter email'
      },
      validators: {
        validation: Validators.compose([Validators.required, ValidationService.emailValidator])
      }
    }, {
      className: 'col-md-12',
      key: 'password',
      type: 'input',
      templateOptions: {
        type: 'password',
        label: 'Password',
        placeholder: 'Password',
        pattern: ''
      },
      validators: {
        validation: Validators.compose([Validators.required])
      }
    }]
  }];
```

**Comment by franzeal** [comment]
You can determine that from the `form` you pass to the `FormlyForm`.  That `form`, a [FormGroup](https://angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html), inherits from [AbstractControl](https://angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html) which has properties for valid, invalid, etc.

Demo Plunker:  http://embed.plnkr.co/5VOGurddzHJFWn2Qz4Yx/

**Comment by laterbreh** [comment]
Fantastic! I knew it was something simple. I'm going to read up more on the standard form documentation so I can not make silly mistakes like this again. 

Thank you for your input!
