### ISSUE TITLE
How to handle dynamic options in 'select' type

### ISSUE THREAD

**Issue by shohrukh92** [formly-js/ng-formly#414]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

Hi all!
Is there a way in **ng-formly** to handle dynamic options in select type?
(similar [issue](https://github.com/formly-js/angular-formly/issues/202) from **angular-formly**)

**Comment by franzeal** [comment]
Certainly.  If you can do it in Angular, you can do it in ng-formly.  This plunker demonstrates a customized select that's intended to work with objects (group capability isn't fleshed out), restore selection, and handle default values:

https://plnkr.co/edit/lJicJlV1Q2lnbXP9dsUF?p=preview

There's certainly more that could be done to flesh it out, but it currently meets my use case.  I handle multiple selects with a separate type that extends this one, just supplying a different template.

**Comment by shohrukh92** [comment]
Thanks for these examples. Is there a way to use arrow function instead of `onInit: function() {...}` and still get the access to `to.options` param?

**Comment by franzeal** [comment]
Not that I'm aware of.  The lifecycle callbacks bind the field component instance to "this" when invoking the callback, which using an arrow function overrides:
https://github.com/formly-js/ng-formly/blob/6cafbd06f9eee95bdcaf397b472b5db63b985ff9/src/core/templates/field.type.ts#L43

**Comment by shohrukh92** [comment]
This is an answer for my last question I believe :)
https://github.com/formly-js/ng-formly/blob/master/demo/src/app.component.ts#L171
