### ISSUE TITLE
Custom type "extends" Input type but not "extends" Input features

### ISSUE THREAD

**Issue by hnguyenec** [formly-js/ng-formly#415]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```

**Current behavior**

I follow the example
https://plnkr.co/edit/b0TOg5IYPCDp6fZFyNes?p=preview
I can see `name: 'datepicker', component: FormlyDatePicker, extends: 'input'`
But I dont know what configs/functions that 'datekicker' will inherit from Input type
I put keyup event in
`this.fields =  [
      {
        key: 'date',
        type: 'datepicker',
        templateOptions: {
          label: 'Username',
          required: true
          keyup: () => {
            debugger;
          }
        }
      }
    ];`
But it never being called

**Expected behavior**

when extends from base component, should bring all methods/configs/events across
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, Visual Studio Code
* **Angular version:** 2.0.X

4.0.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =   7.6.0

**Comment by mohammedzamakhan** [comment]
DatePicker is a custom type that is created in that plnkr, you will have to add the methods that ngbDatepicker provides to the FormlyDatePicker using how FieldTypes are defined and use them
