### ISSUE TITLE
Browse File Button

### ISSUE THREAD

**Issue by ruchitFirstAI** [formly-js/ng-formly#418]
Hello Team,

Recently I have downloaded this node module, and I am wondering about how to use browse file button functionality or something related to that.

**Comment by mohammedzamakhan** [comment]
Just create your own `FieldType`!

**Comment by franzeal** [comment]
@ruchitFirstAI, you can refer to the [demo](https://github.com/formly-js/ng-formly/blob/master/demo/src/formly/types) or [source](https://github.com/formly-js/ng-formly/tree/master/src/ui-bootstrap) for examples of how to create your own `FieldType`.

Along those lines, you can also wrap other libraries in an Angular [control](https://angular.io/docs/ts/latest/api/forms/index/ControlValueAccessor-interface.html) to embed within your own `FieldType` to play nicely with Angular's reactive forms.

**Comment by ruchitFirstAI** [comment]
Hello Team,

Thanks for your suggestion.
