### ISSUE TITLE
Support for Angular 4 and Roadmap for the future developments

### ISSUE THREAD

**Issue by williegreat** [formly-js/ng-formly#419]
Hello,

In the past we have had a very good experience in working with **formly** on a large and complex Angular 1.X application.
We are starting a brand new project in Angular 4 and we want to heavily rely on **ng-formly**. 
We started to integrate our project(based on Angular-CLI) with **ng-formly** and encountered with dependencies issues(like **npm WARN ng2-formly@2.0.0-beta.14 requires a peer of @angular/forms@^2.2.0 but none was installed.** - our @angular/forms version is 4.0.1).

Our concerns are : 
We see that dev-dependencies are not up to date.
Will the **ng-formly** support next versions of Angular (like 4)?
When  the release version of **ng-formly is planned to be ?

Thank you very much in advance

**Comment by franzeal** [comment]
The current release candidate supports Angular 4 and is backwards compatible with version 2.
https://github.com/formly-js/ng-formly/releases/tag/1.0.0-rc.4

Your package references need to point to "ng-formly" as opposed to "ng2-formly".
