### ISSUE TITLE
Cannot reset Wrappers list for existing types

### ISSUE THREAD

**Issue by hnguyenec** [formly-js/ng-formly#420]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

I am generating data to pass to formly
If type doesnt have 'description' I set wrappers = ['fieldset'] only
But when it is rendered, still render with label wrapper, it means it still get default wrappers=['fieldset', 'label']

However, if using **wrapper** it works 
even got the warning of : 'wrapper is deprecated. Use 'wrappers' instead.'
**Expected behavior**

wrappers list to be able to override
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by franzeal** [comment]
I don't think setting the wrappers on the field should override the wrappers on the type.  The way ng-formly's "wrappers" behave is in line with angular-formly's.  

In this case, "wrapper" was added to subsequently ease migration from angular-formly.  Given that, the behavior of "wrapper" would appear to be a bug and likely not what was intended.

The example in the demo involving a horizontal input would seem like a potential way to accomplish what's desired here.  A template manipulator might be another option.

My only concern would be that the current behavior be preserved as the default.  If this enhancement came to fruition, I'd hope that it would require something explicit on the field to indicate the intention of overriding the type's wrappers as opposed to simply adding wrappers to the field.

**Comment by hassanthegooner** [comment]
Think I've got a similar problem. I've set `wrapper: null` in my JSON but the description wrapper still shows?

**Comment by mohammedzamakhan** [comment]
Check the usage is the demo example, you should create a new type, using the existing component

https://github.com/formly-js/ng-formly/blob/a76b3060f3386710352798728c44f8acd363d1e0/demo/hello.ts#L543
