### ISSUE TITLE
On demo "import { clone } from '../../../../src/core/utils';" doesn't exist. 

### ISSUE THREAD

**Issue by erickconcepcion** [formly-js/ng-formly#421]
On demo /src/formly/types/repeatedSection.ts line 4 thiere is a call to import { clone } from '../../../../src/core/utils'; but this module doesn't exist. 
[ x ] bug report =>https://github.com/formly-js/ng-formly/blob/master/demo/src/formly/types/repeatedSection.ts

**Current behavior**
'../../../../src/core/utils' isn't on repo

**Expected behavior**
the module must be added.

**Comment by aitboudad** [comment]
see #422
