### ISSUE TITLE
FormlyModule.forRoot(NgFormlyConfig)

### ISSUE THREAD

**Issue by ruchitFirstAI** [formly-js/ng-formly#423]
Hello Team,

I am using angular 4, but when I am trying to import this "FormlyModule.forRoot(NgFormlyConfig)", at that time I faced error

 
" Function calls are not supported. Consider replacing the function or lambda with a reference to an exporte
d function (position 8:34 in the original .ts file) "

Thanks,

**Comment by franzeal** [comment]
I believe that's particular to AoT compiliation.  I would try setting the anonymous functions used throughout the config options in demo\src\formly\index.ts to reference an exported function as the error message suggests.

e.g.
```typescript
validators: {
    date: control => !control.value || control.value.match(/^(0?[1-9]|[12][0-9]|3[01])[\/\-](0?[1-9]|1[012])[\/\-]\d{4}$/) }
}
```

becomes:

```typescript
export function dateValidator(control: FormControl) {
    return !control.value || control.value.match(/^(0?[1-9]|[12][0-9]|3[01])[\/\-](0?[1-9]|1[012]);
}
```
and
```typescript
validators: {
    date: dateValidator
}
```

**Comment by nikul1993** [comment]
I have started angular 4 project. this is my first angular project and I am facing the same issue. what is the shortest way to solve that. if you give example, that more use full.

Thanks in advance.

**Comment by ruchitFirstAI** [comment]
Hello Team, 
can you please rephrase above things, so we will get more idea about how to use in angular4.

**Comment by aitboudad** [comment]
@ruchitFirstAI can you provide us your `NgFormlyConfig`

**Comment by ruchitFirstAI** [comment]
Yea sure @aitboudad 

Below are the ngFormlyConfig


import { Validators } from '@angular/forms';
import { ConfigOption } from 'ng-formly';

export const NgFormlyConfig: ConfigOption = {
  
  validators: [{ name: 'required', validation: Validators.required}],
  validationMessages: [
    { name: 'required', message: (err, field) => `${field.templateOptions.label} is required.`},
    { name: 'invalidEmailAddress', message: 'Invalid Email Address' },
    { name: 'maxlength', message: 'Maximum Length Exceeded.' },
    { name: 'minlength', message: (err) => {
        return `Should have atleast ${err.requiredLength} Characters`;
      },
    },
    { name: 'not_matching', message: 'Password Not Matching' },
  ],
};

**Comment by aitboudad** [comment]
@ruchitFirstAI instead of lambda function used in `required` and `minlength`:

```ts
export const NgFormlyConfig: ConfigOption = {
    { name: 'required', message: (err, field) => `${field.templateOptions.label} is required.`},
  ...
}
```

you should pass an exported function:

```ts
export function requiredMessage(err, field)  {
    return `${field.templateOptions.label} is required.`;
}

export const NgFormlyConfig: ConfigOption = {
  { name: 'required', message: requiredMessage },
  ...
}
```

**Comment by ruchitFirstAI** [comment]
Hello @aitboudad 
It's Working and helpful.
Thanks for your support...!
