### ISSUE TITLE
the validation of repeatSection custom type doesnt not affect the main Form valid status

### ISSUE THREAD

**Issue by hnguyenec** [formly-js/ng-formly#426]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

I have tried the example, remove all types except for the repeatSection
Model was set to
`this.user = {
      investments: [{}
      ],
    };`

Also output the main form valid status

Even all sub required types of repeatSection type are Invalid
The main form status still TRUE

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
see #427
