### ISSUE TITLE
Click on Submit validation message call

### ISSUE THREAD

**Issue by nikul1993** [formly-js/ng-formly#429]
Hello team,

i have disable the submit button using this.

<button [disabled]="form.invalid" type="submit" class="btn btn-primary">Submit</button>

but i am wondering that how to call validation message on click submit button.

**Comment by aitboudad** [comment]
do you want to display message validations without submit form, right?
The messages is displayed when field is marked as touched see [field.ts#L25](https://github.com/formly-js/ng-formly/blob/master/src/core/templates/field.ts#L25) but you can change it by overriding `valid` method and if you want to do it manually just call `markAsTouched` method:
Try with:
```ts
  form.markAsTouched();
```

**Comment by nikul1993** [comment]
@aitboudad 

i want like this https://codepen.io/jaycbrf/pen/iBszr click on send button without fill the input.

when user click on submit button that time validation message come.

**Comment by aitboudad** [comment]
ok I see, I'll try provide you a working example in the next few days (probably tomorrow)

**Comment by nikul1993** [comment]
hello @aitboudad 

recently we have talk about this issue, have you find any solution, please let me know.

thanks.

**Comment by aitboudad** [comment]
I'm on it right now and sorry for the delay ;)

**Comment by aitboudad** [comment]
Firstly update `ng-formly` into `rc7` then apply the following changes: https://github.com/formly-js/ng-formly/pull/434/commits/1166bf8f70a21886b692c03531aacdb39e775605

**Comment by nikul1993** [comment]
hello @aitboudad 

Thanks for you quick replay.

i have reset my form using this 

resetForm() { 
    this.form.reset({     
		applicationname:'',
		company:'',
		applicationlogo:'',
		applicationorder:'',
		gstatus:'',
    });    
  }

when i click on reset button it also show me error message instated of blank the input field.

**Comment by aitboudad** [comment]
@nikul1993 can you open a new issue with a reproduction example thanks!

**Comment by paigudepooja** [comment]
@aitboudad I want to call a function on click of particular key in input text. How can I achieve that ?

**Comment by aitboudad** [comment]
@paigudepooja it's better to fill an new issue, anyway have you tried `keyup` callback ?

```ts
    {
      templateOptions: {
        keyup: (field, event) => {
          console.log(event);
        }
      },
    },
```

**Comment by paigudepooja** [comment]
@aitboudad Thank you for the response. Its working and from next time i will fill an new issue.
