### ISSUE TITLE
Type Configuration Validation

### ISSUE THREAD

**Issue by zipilid** [formly-js/ng-formly#435]
I wrote custom field type, that has a validation:

types: [
        {
            name: 'fieldType', extends: 'input', defaultOptions: {
                validators: {
            validation: FormlyValidationService.doublenumberValidator,
                },
            },
        }
]

in the schema, I have a field that uses the new type:

 {
                    "key": "nameOfField",
                    "type": "fieldType",
                    "templateOptions": {
                        "type": "fieldType",
                        "label": "nameOfField",
                        "placeholder": "nameOfField",
                        "min":"55",
                        "max":"90",
                    }
                }

now, I dont know why, but when I use the min\max keys in the templateOptions, my custom validation is ignored.

There is another question about the validation service function.
in the validation service I have this function:

    static doublenumberValidator(control) {
        if (!control.value) {
            return null;
        }
//...extra code
        /**
        * validate min & max
        */

        var value = parseFloat(control.value);
        if (!(value >= parseFloat(?control.min?) && value <= parseFloat(?control.max?))) {
            return { invalidRange: true };
        }
        return null;
    }

the ?control.min/max? means that here I want to get the min/ max values from the schema field's templateOptions, but I don't have them in the control object that I get.
where can I get them from?

**Comment by franzeal** [comment]
The control is a [FormControl](https://angular.io/docs/ts/latest/api/forms/index/FormControl-class.html).  I'm not aware of a nice way to do what you want.  The validators are only passed the `FormControl`:  https://github.com/formly-js/ng-formly/blob/master/src/core/services/formly.form.builder.ts#L199

I worked around this (for both expressions and validators) by binding these when the field is constructed so that I can give those expressions the instanced field for context (`this`).

**Comment by zipilid** [comment]
I didn't clearly understand the work around.
could you plz attach a code sample?
Thanks.

**Comment by franzeal** [comment]
http://plnkr.co/edit/tq0gqBvbtjxWm1vC9Rou?p=preview

It isn't perfect, but gives you the gist.  It fits my use case, but for the example I also wanted validation messages to come through.  I couldn't get that to occur without including a dummy validator on the field and haven't figured out why.

**Comment by zipilid** [comment]
Gracias! worked perfect for me.
