### ISSUE TITLE
reproduction example

### ISSUE THREAD

**Issue by nikul1993** [formly-js/ng-formly#436]
@aitboudad 

as per new changes in plugin can you modify the example. so that we have get idea about click on submit button validation. related to this issue : Click on Submit validation message call #429 

and right now i face an issue that i click on reset button it also show the validation messages. in current example you click on submit button 2 times and click on reset button then validation messages shows.

**Comment by aitboudad** [comment]
@nikul1993 you just need to reset `submitted` option:

```ts
resetForm() {
  this.options.formState.submitted = false;
  ....
}
```

**Comment by nikul1993** [comment]
Hello @aitboudad 
It's Working and helpful.
Thanks for your support...!

**Comment by aitboudad** [comment]
great!
