### ISSUE TITLE
Problem with updating the data

### ISSUE THREAD

**Issue by Gaedr** [formly-js/ng-formly#437]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
I'm doing a component compound of two elements, the left side have a list of elements and the right side the form generated with formly.

Every type of element of the left side have different fields that is because sometime I click on the element produce an event that load data and the field require and substitute actual form data and field with the new ones.

This is component image:
![ejemplo](https://cloud.githubusercontent.com/assets/8356309/26637864/efe33e6c-4620-11e7-8dec-1b9cb3e3960d.png)

**Expected behavior**
Any time I click element the field and model updating ( I check every time the data was arrive), the form changes an appear the new fields but the data doesn't changes. I try to reset the form every time I click but no results.

* **Angular version:** 4.1.0 
* **Language:** TypeScript 2.3.2

**Comment by aitboudad** [comment]
Hi @Gaedr It would be helpful if you can provide us a reproduction example,
refering to the data please ensure you have passing a new ref of object

```ts
data = { ...newData };
```

**Comment by Gaedr** [comment]
It's difficult to export this functionality to plunkr because it is a part of a big component and it's too hard to isolate functionality, so this is the code referenced to issue.

This is html referenced to formly:
``` html
<div class="card-block" *ngIf="modelSelected && modelSelectedFields && !loading; else no_content">
    <form class="formly" role="form" novalidate [formGroup]="form" (ngSubmit)="onSubmit(form)" *ngIf="dataSelected">
         <formly-form [model]="dataSelected" [fields]="modelSelectedFields" [form]="form" [(options)]="options">
              <div class="clearfix"></div>
              <div class="pull-right">
                <button type="submit" class="btn btn-primary">
                  {{ nodeSelected.mode == 'edit'? 'Update' : 'Add' }} 
                  <span class="text-capitalize">{{ nodeSelected.type }}</span>
                </button>
              </div>
        </formly-form>
    </form>          
</div>
```
And this is the code that load component:
``` typescript
private loadComponent() {
        this._nodeSelected.subscribe( (node) => {
            this.errorOnLoading = false;
            this.loading = true;
            
            if (node) {              
                this.nodeSelected = node;
                this.modelSelected = this.getModelByNode(node);

                if (node.mode === 'edit') {
                    const data$ = this.getResourceByNode(node);
                    if (data$) {
                        data$.get( { id: node.id } ).$observable.subscribe(
                            (data) => setTimeout(() => { this.dataSelected = Object.assign({}, data)  }) ,
                            (error) => {
                                console.error('Error', error);
                                this.errorOnLoading = true;
                            },
                            () => this.loading = false,
                        );
                    } else {
                        this.loading = false; 
                    }
                } else {
                    this.loading = false; 
                }
            }
        });
    }
```
`node`contains a bit information about component like type, id and name.
```typescript
export interface INodeElement {
  id?: number;
  name?: string;
  type: string;
  mode: 'add' | 'edit';
}
```

`getModelByNode()` retrieves an object with a lot of information about element even `FormlyFieldConfig` variable:
```typescript
export interface IElementModel {
  key: string;
  icon: string;
  plural?: string;
  duplicate?: boolean;
  parent?: string;
  childs?: string[];
  fields?: FormlyFieldConfig[];
  extraFields?: string[];
  actionCallback?: Observable<any>;
  [field: string]: any;
}
```
Other useful methods to understand the code:
```typescript
// The variables of the class
protected nodeSelected: INodeElement;
protected modelSelected: IElementModel;
protected dataSelected = null;

// Method to obtain the fields
protected get modelSelectedFields(): FormlyFieldConfig[] | FormlyFieldConfig {
    return this.modelSelected ? this.modelSelected.fields : [];
}
```

**Comment by mohammedzamakhan** [comment]
@Gaedr you don't have to make exactly what you are doing in your project, just a small dummy example which demos the behavior should be enough.

**Comment by Gaedr** [comment]
This is a bit example of a dummy demo
http://plnkr.co/edit/LnJ4jjSM9OX6t0k2LpGT?p=preview

**Comment by mohammedzamakhan** [comment]
@Gaedr that example doesn't work on my system 😞

**Comment by aitboudad** [comment]
@mohammedzamakhan FormlyBootstrapModule is missing on the provided example you just need to include it on ngModule.

**Comment by aitboudad** [comment]
I left you this issue :)

**Comment by Gaedr** [comment]
I fixed the plnkr adding the `FormlyBootstrapModule`

**Comment by mohammedzamakhan** [comment]
@Gaedr I see that you change fields based upon logic.

I think the best solution to this is to use `hideExpression` and solve it, see the working example

http://plnkr.co/edit/uXu1bzLqnmbc3nkMshql?p=preview

**Comment by franzeal** [comment]
Try this:
http://plnkr.co/edit/c0MTUdQJfMDU3SfwYRZ8?p=preview

In general, if you recycle your `formly-form` with disparate fields, it's a good idea to reset them the same time you're resetting the model (options too if you're using those) as well as deep copy the fields you ever give to the `formly-form`, because it will mutate them with additional state which may cause odd behavior.
