### ISSUE TITLE
radio buttons is exclusive in different Fields

### ISSUE THREAD

**Issue by hnguyenec** [formly-js/ng-formly#444]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

I have checked: https://ng2.angular-formly.com/guides/introductory-example.html
Title 1 and Title 2 are radio button typed field
Select an option in either Title1 or Title 2 will "exclusive" another
**Expected behavior**

An Option of a radio-typed field should "exclusive" others of the same field
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by hnguyenec** [comment]
solved

**Comment by HarshitChhipa** [comment]
How you have solved it??
Would you be able to help?
