### ISSUE TITLE
Dependency between fields of different groups

### ISSUE THREAD

**Issue by hnguyenec** [formly-js/ng-formly#445]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**

 I have been using idea of formly-repeat-section to group all related fields in groups
Eg: 
- groupA has field1, field2
- group B has field3, field4
The model will be generated corresponding : 
formModel = {
   "groupA": [ {
       "field1": "",
       "field2": ""
    } ],
   "groupB": [ {
       "field3": "",
       "field4": ""
    } ]
}

Everything is working fine
However, if field3 of groupB depends on selected value of field1 in groupA,
the hideExpression of field3 will be: 'formState.originalModel["groupA"][0]["field1"] != "ABC"'
and field3 will never being shown regardless of value changes of field1

with
formOptions = {
   formState: { originalModel: formModel}
}

**Expected behavior**

Value changes of Field1 should trigger hideExpression of Field3 even they are in different groups
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by franzeal** [comment]
I typically do this type of complex inter-field communication between some combination of services, observables (either part of the service or the form/controls themselves), and lifecycle events.

If you want to put together a minimal plunker to set up the problem I'd be happy to toy with it.

**Comment by hnguyenec** [comment]
Thanks franzeal, I have decided to go with fieldGroup so that model will be flat as 1 level json data
