### ISSUE TITLE
what is the latest version?

### ISSUE THREAD

**Issue by karser** [formly-js/ng-formly#446]
[CHANGELOG](https://github.com/formly-js/ng-formly/blob/master/CHANGELOG.md) says the latest version is 1.0.0-rc.8
[npm package](https://www.npmjs.com/package/ng-formly) says it's 1.0.0-rc.9
The latest github [tag/release](https://github.com/formly-js/ng-formly/tags) is 1.0.0-rc.7

**Comment by aitboudad** [comment]
fixed, the last version is `1.0.0-rc.9` and there no relevant changes between `rc.8` and `rc.9`.
