### ISSUE TITLE
multicheckbox validation issue

### ISSUE THREAD

**Issue by nikul1993** [formly-js/ng-formly#448]
Hello team,

 I just found that in radio button it take a validation message on submit button but in multicheckbox it can't show the validation message.

**radio button:**
                       {
				type: 'radio',
				key: 'LoginTypes',
				className: 'col-sm-4 col-xs-12',
				templateOptions: {
					options: [{
						key: 'google',
						value: 'Google',
					}, {
						key: 'facebook',
						value: 'Facebook',
					}, {
						key: 'twitter',
						value: 'Twitter',
					}],
					label: 'Login As *',
				},
				validators: {
					validation: Validators.compose([Validators.required])
				}
			},

**multi checkbox:** 
                      {
				type: 'multicheckbox',
				key: 'LoginTypes',
				className: 'col-sm-4 col-xs-12',
				templateOptions: {
					options: [{
						key: 'google',
						value: 'Google',
					}, {
						key: 'facebook',
						value: 'Facebook',
					}, {
						key: 'twitter',
						value: 'Twitter',
					}],
					label: 'Login As *',
				},
				validators: {
					validation: Validators.compose([Validators.required])
				}
			},

**Comment by mohammedzamakhan** [comment]
can you post the link for plnkr please.

**Comment by nikul1993** [comment]
@mohammedzamakhan 

Sorry for delay,
**Check this link** : https://plnkr.co/edit/sMh3QT3O2vcvUKNc2OfP?p=preview

click on submit button, there is radio working fine but multicheckbox is not so can you please help will appreciate 

Note : we need at least one checkbox require 

Thanks

**Comment by franzeal** [comment]
A couple of issues here.  First is you can't use the built-in required validation here (Angular or ng-formly for that matter).

Second, the built-in mutlicheckbox type handles its own control creation but isn't setting the validation on the form group it creates.

I've updated your plunker to address the above:
https://plnkr.co/edit/v7sR6ess9GF8cWjbpDY1?p=preview

**Comment by nikul1993** [comment]
@franzeal 

Thanks for the quick response. it is really help full.

@mohammedzamakhan  can you publish this changes.

thanks

**Comment by aitboudad** [comment]
ok I'll try to release today.

**Comment by aitboudad** [comment]
done!

**Comment by nikul1993** [comment]
Thanks @aitboudad
