### ISSUE TITLE
repeatSection issues

### ISSUE THREAD

**Issue by andriy101** [formly-js/ng-formly#452]
at "Introduction example" (https://ng2.angular-formly.com/guides/introductory-example.html), initial values within repeatSection are always the same and equals to the fist element in array:
`{
      "investmentName": "Formly",
      "investmentDate": "02-11-2001",
      "stockIdentifier": "FO"
    }`

although the initial model looks like:
`[
    {
      "investmentName": "Formly",
      "investmentDate": "02-11-2001",
      "stockIdentifier": "FO"
    },
    {
      "investmentName": "Formly Website",
      "investmentDate": "02-11-2001",
      "stockIdentifier": "FW"
    }
  ]`
"Formly Website" and "FW" are not displayed in their text fields.

now, If I type anything in any of textfields (does not matter which model element, may be first or second), values in both models are changed to this new value, although only one model should be changed. 

The same behavior is when adding or removing new items

please assist,
thanks

**Comment by aitboudad** [comment]
Hi, the doc example is not up to date, please follow the demo example in https://github.com/formly-js/ng-formly/tree/master/demo
The repeat section can be found in https://github.com/formly-js/ng-formly/blob/master/demo/src/formly/types/repeatedSection.ts

we will focus on doc once we release the `v1.0`

**Comment by andriy101** [comment]
thanks, works as expected,
BTW, if you need some help coding/developing/fixing - I would be glad to help
