### ISSUE TITLE
how to add custom Attribute in input

### ISSUE THREAD

**Issue by nikul1993** [formly-js/ng-formly#464]
Hello team,

I need to add custom attribute in input field for add angular plugin functionality so can you please provide option for **custom attribute** it will fix my many issues and very important for us.

Thank you very much for your support 😃 .
Best regards,

**Comment by mohammedzamakhan** [comment]
@nikul1993 for now we do not support adding custom attribute, but yes, you can support it by creating a new type in your project.

**Comment by nikul1993** [comment]
@mohammedzamakhan 

Can you give me some detail about this. I am new in angular 4

**Comment by mohammedzamakhan** [comment]
https://ng2.angular-formly.com/guides/ng-bootstrap-datepicker.html This example has created a new type `datepicker`. check app.ts of the example

**Comment by nikul1993** [comment]
Thanks @mohammedzamakhan
