### ISSUE TITLE
[v2][npm] switch into `@ng-formly` or `@ngx-formly` ?

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ng-formly#466]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

This will allow use to group the dependencies:
 
-  `@ng-formly/core`
-  `@ng-formly/ui-bootstrap`
-  `@ng-formly/ui-material`

**Comment by mohammedzamakhan** [comment]
Or maybe just @formly, since we have already registered and it is more easy to remember?

**Comment by aitboudad** [comment]
@mohammedzamakhan 
I prefer `ngx` prefix as it easy to remember too, commonly used in angular wild and it simplify to find good name for templating packages (`@ngx-formly/ui-bootstrap` vs `@formly/angular-ui-bootstrap`)

**Comment by mohammedzamakhan** [comment]
Sure, lets go for @ngx-formly, but for templating packages, lets not have either ui-bootstrap or angular-ui-bootstrap, since we do not want to give any resemblance between formly and https://angular-ui.github.io/bootstrap/
