### ISSUE TITLE
repeatSection does not properly show initialized model

### ISSUE THREAD

**Issue by ultimafirez** [formly-js/ng-formly#470]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Initializing the repeat section with a model array of two objects does not properly render the second object in the form. The repeatSection shows two copies of the first object initialized in the model. Additionally, the add button will continue to add copies of the first model.

**Expected behavior**
If the repeat section is initialized with the following model:

this.user = {
      investments: [
        {
          investmentName: 'Formly',
          investmentDate: '02-11-2001',
          stockIdentifier: 'FO',
        }, {
          investmentName: 'Formly Website',
          investmentDate: '02-11-2001',
          stockIdentifier: 'FW',
        },
      ],
    };

The repeat section should show two distinct sections rather than 2 copies of the first section as demonstrated in this plunkr: https://plnkr.co/edit/nAef2k9vrkDxwWsMwQPu?p=preview
Furthermore, pressing the add button will add a copy of the first section.
I have made minimal changes to the plunkr on the demo website to reproduce this issue. I am also seeing this issue in the current release (1.0.0-rc.10)

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/nAef2k9vrkDxwWsMwQPu?p=preview
When the repeat section first renders, you will see the described behaviour above. The reset model function also does not work.

**What is the motivation / use case for changing the behavior?**
Need a working repeat section that renders each section properly when given a model. As with normal use cases of ng-formly, our backend provides the form data and we need to show this data on the form.

**Please tell us about your environment:**
Irrelevant.

* **Angular version:** 2.0.X
2.4.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
Irrelevant

**Comment by franzeal** [comment]
https://plnkr.co/edit/l6peH8jFj4ygkWB2LQA4?p=preview

Update your `repeatSection` type to match what's in the source [demo](https://github.com/formly-js/ng-formly/blob/master/demo/src/formly/types/repeatedSection.ts).

You cannot reset the model with the form or simply by changing the model binding, particularly with a `FormArray` involved (which is what the `repeatSection` utilizes).  Formly sits on top of Angular's reactive forms, so if you change the model structure (as is the case for particularly for arrays) the reactive control structure needs to be rebuilt.  This is what the options.resetModel function is intended to do; I would recommend providing a new fields and model instance to formly in most cases over using that helper function, but it may do the business if you have logic in your fields that needs to initialize other parts of the form (e.g. initializing parts of the form from another data feed which is where I've used this specifically).

**Comment by ultimafirez** [comment]
Thanks @franzeal. I guess the repeatSection I used was from the outdated demo website. Your solution works!

**Comment by ultimafirez** [comment]
@franzeal One thing I noticed with your solution is that the ngSubmit from the form is fired every time a new investment is added. Is this intentional or another defect?
