### ISSUE TITLE
Load JSON with http service

### ISSUE THREAD

**Issue by bhupendrasolanki251185** [formly-js/ng-formly#472]
I have create JSON file and put the valid json structure as per fomly, and load with http service but it is not working, but if i put that same json in component then it is working fine

JSON file 
[
    {
        "fieldGroupClassName": "row",
        "fieldGroup": [
            {
                "key": "firstName",
                "type": "input",
                "className": "col-md-6",
                "templateOptions": {
                    "type": "text",
                    "label": "First Name",
                    "id": "txtFname",
                    "tabindex": "1"
                },
                "validators": {
                    "validation": "Validators.compose([Validators.required, Validators.maxLength(10), Validators.minLength(2)])"
                },
                "validation": {
                    "show": true,
                    "messages": {
                        "className": "",
                        "required": "First name is required",
                        "minlength": "First name must be atleast 2 character long.",
                        "maxlength": "First name cannot be more than 10 character long."
                    }
                }
            }
        ]
    }
]

Diffrence between component and JSON file structure is
In JSON file i have to provide double quotes [" "] to create valid json and in component i have not provide any double quotes [" "]

**Comment by franzeal** [comment]
```TypeScript
"validators": {
"validation": "Validators.compose([Validators.required, Validators.maxLength(10), Validators.minLength(2)])"
}
```

You can't take a JavaScript object that includes function references, escape those references with double quotes and expect things to work.  There are examples in the [demo](https://github.com/formly-js/ng-formly/blob/master/demo/src/app.component.ts#L190) that will jive with fields declared in JSON.

**Comment by bhupendrasolanki251185** [comment]
As suggested in example it is showing me an error and i have made entry in JSON as suggested

**JSON Entry**
 {
                fieldGroupClassName: 'row',
                fieldGroup: [
                    {
                        className: 'col-md-6',
                        type: 'input',
                        key: 'street',
                        validators: {
                            validation: ['required'],
                        },
                        validation: {
                            messages: {
                                required: 'WOW!! Enter the Street',
                            },
                        },
                        defaultValue: '204 Causley Ave. ',
                        templateOptions: {
                            label: 'Street',
                            placeholder: '604 Causley Ave. ',
                            description: 'Enter a valid US Address',
                        }
                    }
                ]
            }

**ERROR**
Error: Uncaught (in promise): Error: [Formly Error] There is no validator by the name of "required"
Error: [Formly Error] There is no validator by the name of "required"

**Comment by franzeal** [comment]
You can't reference a validator as a string without defining it in the formly config.  Please refer to the [demo](https://github.com/formly-js/ng-formly/blob/master/demo/src/formly/index.ts#L24).

**Comment by bhupendrasolanki251185** [comment]
I have checked provided demo sample but in that sample only required validation is working,
className: 'col-md-6',
type: 'input',
key: 'street',
validators: {
validation: ['required'],
},
but i needs to apply maxlenth, minlenth, pattern and custom validation then it is not working, and please provide my working sample for that with all the validation.

**Comment by aitboudad** [comment]
@bhupendrasolanki251185 you must define them in the config section in order to use them in the form, similar to [required example](https://github.com/formly-js/ng-formly/blob/master/demo/src/formly/index.ts#L24)
