### ISSUE TITLE
How to add a class to a form input only and not on the formly-field ?

### ISSUE THREAD

**Issue by DDeis** [formly-js/ng-formly#473]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I'm using Bootstrap 4 and I got a formly form working with this setup:
```typescript
const fields: Array<FormlyFieldConfig> = [
  {
    fieldGroupClassName: 'row',
    fieldGroup: [
      {
        key: 'firstname',
        type: 'input',
        className: 'col',
        ...
      },
      {
        key: 'lastname',
        type: 'input',
        className: 'col',
        ...
      }
    ]
  },
 ...
];
```

However, I want to use the `form-control-sm` class to save up space in my form. ([Bootstrap 4 documentation](https://v4-alpha.getbootstrap.com/components/forms/#control-sizing))

It's supposed to be used like that:
```html
<input class="form-control form-control-sm" type="text">
```
But I can't find a way to add a class to the input itself. At first I tried naively to add it to the formly field className but the class gets applied to `<formly-field>` . I've searched in ng-formly documentation and issues but found nothing relevant.

What would be the way to achieve what I want ?

**Comment by ultimafirez** [comment]
What you can do is create a custom field type that takes in a templateOption property like "inputClass" and have it bind to the input's ngClass.

Example: https://plnkr.co/edit/k0kkTqhxquhwsQuN8pmb?p=preview

**Comment by DDeis** [comment]
Hello @ultimafirez,

Thank you for your response, it works perfectly! I was heading to a similar solution but wasn't what was the good way of doing it. Your example with additional properties will also be a great help to create other custom type I'm thinking about.

Your answer helped me to better understand how ng-formly works, but I'm still trying to sort it all out and I still have some interrogations:

- First, I see in `src/ui-bootstrap/src/ui-bootstrap.config.ts` that `input` type has `fieldset` and `label` wrappers, how come that with your solution we don't need to declare them in order to have the label and validation message displayed ?

- Is it a good idea if the custom input type extends the original FormlyFieldInput ? I've tested it and it works, in this case we don't gain much but in general would it be cleaner this way our would you recommand against it ?

- Also I modified the inputClass getter to conditionnaly add the `form-control-danger` class but I'm not sure if this is the good way of doin't it: [https://plnkr.co/edit/oO55ySLatrcqg1BaS1df?p=preview]()

And again, many thanks :)

**Comment by franzeal** [comment]
> First, I see in src/ui-bootstrap/src/ui-bootstrap.config.ts that input type has fieldset and label wrappers, how come that with your solution we don't need to declare them in order to have the label and validation message displayed ?

The import of `FormlyBootstrapModule` will have already configured a type by the name `input`.  When you configure a type by the same name it updates the existing type instance, overwriting its properties except for wrappers.  The relevant places in the source that enable this behavior:
https://github.com/formly-js/ng-formly/blob/master/src/core/src/services/formly.config.ts#L69 (type instance will be retained)
https://github.com/formly-js/ng-formly/blob/master/src/core/src/services/formly.config.ts#L76 (wrappers instances will be retained)

I have no idea if that's by design.

**Comment by DDeis** [comment]
Thank you it makes sense now !
