### ISSUE TITLE
Setting up of custom field types

### ISSUE THREAD

**Issue by marcodafonseca** [formly-js/ng-formly#474]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
`It is possible to wrap a formly type to add custom styling\layouts, but it is not possible to replace the formly type as removing the <template #formController></template> from the wrapper causes issues.
This then also causes issues with formly's internal validation as it no longer seems to know how to validate fields. It would appear that the validation functionality is more reliant on the field itself as opposed to the values in the model itself.`

**Expected behavior**
`In formly for AngularJS 1 it is possible to configure SetTypes which then completely remove and replace the default formly field types. Is it possible to do the same for ng-formly for Angular2? I can't find any documentation or examples on this...`

**Minimal reproduction of the problem with instructions**
`My scenario is this. One of the things I want to do is replace all <select></select> types with PrimeNG's <q-dropdown><q-dropdown>.`

**Code sample**
My wrapper:
```
<div class="form-group">
    <label attr.for="{{key}}" class="col-md-2 form-control-label">{{to.label}}</label>
    <div class="col-md-10">
        <p-dropdown [filter]="true"
                    [options]="to.options"
                    [(ngModel)]="model[key]"
                    [autoWidth]="false"
                    [styleClass]="'form-control'"></p-dropdown>
        <div [hidden]="true">
            <template #fieldComponent>
            </template>
        </div>
    </div>
</div>
```

I would rather use this:
```
<div class="form-group">
    <label attr.for="{{key}}" class="col-md-2 form-control-label">{{to.label}}</label>
    <div class="col-md-10">
        <p-dropdown [filter]="true"
                    [options]="to.options"
                    [(ngModel)]="model[key]"
                    [autoWidth]="false"
                    [styleClass]="'form-control'"></p-dropdown>
    </div>
</div>
```

but that causes errors are formly doesn't know what to do with its renderer.
Also, as mentioned above, this current setup always returns my forms as `valid = false`, so it completely breaks formly's validation engine... Really not ideal, so I hope someone  can assist with a better solution

**What is the motivation / use case for changing the behavior?**
`The original ability to completely replace a field is far more powerful than only being able to wrap it with your own elements.`

**Please tell us about your environment:**
`NPM, .Net Core, Angular2, Windows 2014 server, Webpack`

* **Angular version:** 2.0.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.3.3

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by mohammedzamakhan** [comment]
Is this something that you are looking for?? https://plnkr.co/edit/PuTTvr8z0isAEvUA9xj6?p=preview

**Comment by marcodafonseca** [comment]
That looks perfect! Thank you! :D
