### ISSUE TITLE
Custom "multilang" field: hide a field without removing its FormControl

### ISSUE THREAD

**Issue by DDeis** [formly-js/ng-formly#475]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I'm trying to create a custom formly type to have multilanguage fields.
So I created a 'multilang' type that generates a field group containing a field for each language and specify the `hideExpression` to have it displayed only when it matches the current lang.

It's working fine for a simple field like an input: [https://plnkr.co/edit/2h9pGMB2ComeqtlLORtm?p=preview](https://plnkr.co/edit/2h9pGMB2ComeqtlLORtm?p=preview)

However I want to use it for a multiselect type I created using [ng-selectize](https://github.com/NicholasAzar/ng-selectize), having one selectize field (non-multilang) adding or removing keywords to a multilang selectize field.

Unfortunately adding and removing automatically keywords is not working properly though it works perfectly when the hideExpression isn't set.

Example with hideExpression:
https://plnkr.co/edit/Zi13Jv6QzIVDZhDvQyb0?p=preview

Example without hideExpression:
https://plnkr.co/edit/kLuTKNvYX7vy13EI5Q20?p=preview

I'm suspecting that's because when the `hideExpression` is `true`, the `FormControl` gets removed as I can see here: https://github.com/formly-js/ng-formly/blob/c7d5384ca73b7f6e3a865e8b2e78021281446d29/src/core/src/components/formly.field.ts#L230.

So how could I hide a field without removing the `FormControl`, or am I missing something or is there a better way to achieve what I want (knowing that I need validation to works also for the hidden fields) ?

**Please tell us about your environment:**

- **Angular version**: 4.X.X
- **Browser**: all
- **Language**: TypeScript 2.3

**Comment by aitboudad** [comment]
I can't figure out what did you get when you use `hideExpression`, both examples works for me!

**Comment by DDeis** [comment]
Hello @aitboudad, thank you for looking into my problem.

It works with hideExpression but the comportement is a bit erratic. 

For instance:

1. **Add `IPTC 2` from the _English_ tab**: then `English keyword 3`, `French keyword 3` and `German keyword 3` are added on each tabs as expected.

2. **Remove `IPTC 2` from the _English_ tab**: only `English keyword 3` will be removed but if we switch lang, `French keyword 3` and `German keyword 3` still appear.

3. **Remove  `French keyword 3` and `German keyword 3` manually and the add `IPTC 2`**: the associated keyword will be added for the current lang but not for the others.

It could be a problem with my implementation of _ng-selectize_ but I don't understand why this is not working though it works perfectly when the hideExpression is not set and we see a keyword field for each languages at the same time :/

**Comment by aitboudad** [comment]
`hideExpression` detach the `formControl` from it's parent so model changes won't take account if the field is hidden and it's an expected behavior.

Right now you can use the bellow workaround in `FormlyMultilangField::buildMultilangField` by moving `hideExpression` inside fieldGroup:

```patch    
--  field.fieldGroup.push(newField);
++  field.fieldGroup.push({
++    fieldGroup: [newField],
++    hideExpression: () => this.to.hideExpression(lang.code),
++  });
```
until we find a better solution for your use-case.

**Comment by DDeis** [comment]
Thanks a lot for the workaround it works like a charm!
