### ISSUE TITLE
Read Only Form | readOnly manipulators for formly

### ISSUE THREAD

**Issue by MaxSassen** [formly-js/ng-formly#481]
**I'm submitting a ...**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[X] support request
```

**Current behavior**
ReadOnly on the form is not available by default.

**Expected behavior**
Same behavior as [angular-formly](http://angular-formly.com/#/example/other/read-only-form)

**What is the motivation / use case for changing the behavior?**
As a User I wan't to be able to enable "edit-mode" and the labels will turn into Inputs.

**What have I tried:**
I found a possible solution that has been made by someone else on angular 1.X [solution](https://gist.github.com/kentcdodds/8efbb18559c58eb82895) and I have tried to convert it into the Angular2 code. I have been successfully added the preWrapper on the FormlyConfig but found out that the parameter template isn't html but the FormlyFieldConfig.

* **Angular version:** 2.0.X

* **Browser:** [all]

 
* **Language:**  TypeScript X.X

**Comment by mohammedzamakhan** [comment]
Check the example from this repo, which shows how to implement read only forms

https://github.com/formly-js/ng-formly/blob/master/demo/src/app.component.ts#L450

**Comment by MaxSassen** [comment]
@mohammedzamakhan thanks but this will only disable the fields, instead of manipulating the html.
`'templateOptions.disabled': '!formState.readOnly',`

**Comment by franzeal** [comment]
@MaxSassen this is a simple approach you could take:
https://plnkr.co/edit/R1ERvqK97HcQjwJymoaT

You'd probably want to adjust how it's styled, but it should give you the idea.

**Comment by MaxSassen** [comment]
@franzeal Thank you for the plunkr url. I will try to implement it into my code.

**Comment by blowsie** [comment]
@MaxSassen disabled is not equal to readonly they have usability differences.
