### ISSUE TITLE
formly is not fully compatible with IE

### ISSUE THREAD

**Issue by hnguyenec** [formly-js/ng-formly#482]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

I have tried with demo on IE11 and the app was not run

![ngformlyie1](https://user-images.githubusercontent.com/635548/28252891-dd888f18-6adf-11e7-8ff8-77f222e4dd64.PNG)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mohammedzamakhan** [comment]
Did you include the polyfills required to run Angular projects and tried?

**Comment by hnguyenec** [comment]
Hi @mohammedzamakhan 
I did install core-js
The polyfills libraries already imported as I can see in bootstrap.ts
```
import 'core-js/es6';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
```

Now, instead of throwing the previous errors, the demo is stuck at Loading ......
Nothing is logged to console as well

**Comment by travis1234** [comment]
it's working great for me in IE11 using angular cli.

Here is my polyfill config:

```javascript

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
```

**Comment by aitboudad** [comment]
it's working for me too, please ensure to import all required polyfills.
