### ISSUE TITLE
How to contribute examples? Here is a plnkr of a custom field component.

### ISSUE THREAD

**Issue by chrisekelley** [formly-js/ng-formly#483]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

Current Introductory example has everything but the kitchen sink. It is useful, but examples that show specific capabilities would be easier to understand.
**Expected behavior**

Folks interested in contributing their own plunks could easily add them to the [Introductory Example/Guide](https://ng2.angular-formly.com/guides/introductory-example.html). Can you point me to where this is hosted and I'll fork it, and submit a PR with my example addition?

If that is not possible, here is the plnkr I forked from the Introductory example to demonstrate a custom field component. It is mostly a copy of the Introductory example, with mostly everything but the custom field code removed. I also removed the use of the deprecated "templateOptions" for "to."

https://plnkr.co/edit/pdys7F?p=info

**Comment by mohammedzamakhan** [comment]
https://github.com/formly-js/ng2.angular-formly.com
