### ISSUE TITLE
Project build fails with AOT and validators in ConfigOption

### ISSUE THREAD

**Issue by DDeis** [formly-js/ng-formly#485]
**I'm submitting a ...**  (check one with "x")
```
[?] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I created an example project to demonstrate a simple use of ng-formly following the [readme](https://github.com/DDeis/ng-formly/blob/master/README.md) and the [introductory example](https://ng2.angular-formly.com/guides/introductory-example.html) when I try to build it with AOT it fails with the following error:

```
➜ ng build --prod
Hash: 71ed1f69b258900aed0f                                                              
Time: 10078ms
chunk    {0} polyfills.71b130084c52939ca448.bundle.js (polyfills) 177 kB {4} [initial] [rendered]
chunk    {1} main.e81f19d3f6b27a436c79.bundle.js (main) 1.09 kB {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.f7457d5ac1e9743fd76f.bundle.js (vendor) 849 kB [initial] [rendered]
chunk    {4} inline.29d3a18937a0453a7d37.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Illegal state: symbol without members expected, but got {"filePath":"/home/ahmad/Documents/Damien/Projets/formly-test-aot/node_modules/@angular/forms/forms.d.ts","name":"Validators","members":["required"]}.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/ahmad/Documents/Damien/Projets/formly-test-aot/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```

**Minimal reproduction of the problem with instructions**

To reproduce the problem you can simply generate a project with `angular-cli` follow the quick start and add this to the `forRoot()` of `FormlyModule` in the `AppModule` (like it is done in the [introductory example](https://ng2.angular-formly.com/guides/introductory-example.html) in `app.ts`):
```ts
{
   validators: [{ name: 'required', validation: Validators.required}],
}
```

Then run `ng build --prod` and you'll get the error.

If you comment the `validators` line, the error is gone.

_To reproduce the error you can also clone the repository: https://github.com/DDeis/ng-formly-test-aot, it contains the code of the reproduction instructions._

**Please tell us about your environment:**

* **Angular version:** 4.3.1

* **Angular-cli version:** 1.2.1
 
* **Language:** TypeScript 2.3

* **Node (for AoT issues):** 
`node --version` =   v8.1.2
`npm --version` = 5.3.0

**Comment by aitboudad** [comment]
Try with:
```ts
export function required(v) { return Validators.required(v); }
....
FormlyModule.forRoot({
   validators: [{ name: 'required', validation: required}],
}),
```

Note: `required` validator is provided by default no need to provide it in the config

**Comment by DDeis** [comment]
Thank you @aitboudad ! I should have thought about trying something like this...

I was just trying simple things I saw in the [readme](https://github.com/formly-js/ng-formly/blob/master/README.md) and [guides](https://ng2.angular-formly.com/guides/) but duly noted for futur developments :)
