### ISSUE TITLE
Dynamically adding element using json is not working properly

### ISSUE THREAD

**Issue by bhupendrasolanki251185** [formly-js/ng-formly#486]
1. Load formly element using angular service,
- So I have created one JSON file and put all UI design JSON schema in that JSON file and load that file using Angular Service.

2. Modify JSON structure as per screen design and implement functionality like Add Element, Delete Element
•	So I have create Add row functionality, which is creating rows dynamically on Add Row button.
•	I have create Delete row functionality, which is remove rows dynamically on Delete button.
**Issues while development**
•	When I have add row dynamically, rows reference like element ids and keys are not updating and If we forcibly update using code then also it is not updated.
•	Outcome for this problem is that there is no unique id generated for elements and we are not able pick element’s data and perform further task.
•	Data for these newly create each element not accessible like text value, checkbox states etc
•	And data model is not uploaded.
•	If we submit data then whole data is not submit because so data is not accessible for these elements.

**Comment by mohammedzamakhan** [comment]
Please provide a plnkr
