### ISSUE TITLE
hideExpression does not interpret less than operator "<" 

### ISSUE THREAD

**Issue by lachko** [formly-js/ng-formly#489]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[ ] support request
```

**Current behavior**
When writing a hideExpression which contains the less than operator "<" the expression is not evaluated and an error is thrown:

```
ERROR ReferenceError: lt is not defined
    at Object.eval (eval at evalStringExpression (http://localhost:4200/vendor.bundle.js:21167:109), <anonymous>:3:1)
```

**Expected behavior**
Operators <,>,<=,>= should be evaluated in hideExpressions

**Minimal reproduction of the problem with instructions**
On any field add the following hide expression that reads a previously entered input and compares it to a static number. For example:
hideExpression: 'model.oral_read_last_selected_nth < "8"'

**What is the motivation / use case for changing the behavior?**
We use hide expression to control the flow of survey questions and we need to be able to compare input to other input or constant numbers or text

**Please tell us about your environment:**
MacOS. VS Code

* **Angular version:** 
Angular 4

* **Browser:** 
Chrome 59.0.3071.115 
 
* **Language:** 
TypeScript

* **Node (for AoT issues):** 
v8.1.3

**Comment by aitboudad** [comment]
Hi, 
I'm not able to reproduce your issue, can you provide us a a plunkr or a repo reproducing the issue?
Thanks!
