### ISSUE TITLE
How to Create Cascaded Select ?

### ISSUE THREAD

**Issue by viki-khairnar** [formly-js/ng-formly#490]
Hi Team , 
Can you please help me achieve creating cascaded select in ng-formly (Angular 2).
I am using angular-formly since a long time. i am upgrading my project from angular 1 to angular 2
but i cant see any example or demo for cascaded select in angular 2. ?

**Comment by viki-khairnar** [comment]
Hi Team, 
Can you please help me quickly, I can not go forward without solution on this issue ?

**Comment by mohammedzamakhan** [comment]
What is cascaded select, can you please paste angular-formly example?

**Comment by viki-khairnar** [comment]
Hi ,
Please find below link for angular-formly demo ,
[](http://angular-formly.com/#/example/other/cascaded-select)

Sample Code :
`vm.formFields = [
  {
    key: 'product',
    type: 'select',
    templateOptions: {
      label: 'Product',
      options: [],
      valueProp: 'name',
      labelProp: 'name'
    },
    controller: /* @ngInject */ function($scope, DataService) {
      $scope.to.loading = DataService.allProducts().then(function(response){
        // console.log(response);
        $scope.to.options = response;
        // note, the line above is shorthand for:
        // $scope.options.templateOptions.options = data;
        return response;
      });

    }
  },
  {
    key: 'options',
    type: 'select',
    templateOptions: {
      label: 'Options',
      options: [],
      valueProp: 'name',
      labelProp: 'name',
    },
    controller: /* @ngInject */ function($scope, DataService) {
        $scope.$watch('model.product', function (newValue, oldValue, theScope) {
          if(newValue !== oldValue) {
            // logic to reload this select's options asynchronusly based on product's value (newValue)
            console.log('new value is different from old value');
            if($scope.model[$scope.options.key] && oldValue) {
              // reset this select
              $scope.model[$scope.options.key] = '';
            } 
            // Reload options
            $scope.to.loading = DataService.allOptionsByProduct(newValue).then(function (res) {
              $scope.to.options = res;
            });
          }
        });

    }
  }
];`

What is the way to achieve same in ng-formly(angular 2) ?

**Comment by mohammedzamakhan** [comment]
You can always subscribe to the form and do whatever you want. This would be possible to do while using this library
