### ISSUE TITLE
Need Support for language translation

### ISSUE THREAD

**Issue by jasminVC** [formly-js/ng-formly#491]
**I need the support for language translation service.**
Hello, I am using a custom language translation service. Actually, I am new to angular2.0 and need the help using ng-formly.

This is my form field.

let formField = [{
      className: 'row',
      fieldGroup: [{
        className: 'col-sm-4 col-xs-12',
        key: 'name',
        type: 'input',
        templateOptions: {
            label: 'Company Name',
            placeholder: i18nService.getTranslation('Company Name'),
            addonRight: {
             class: 'fa fa-user',
             onClick: (to, fieldType, $event) => console.log(to, fieldType, $event),
          },
        },
        validators: {
          validation: Validators.compose([Validators.required])
        },
        expressionProperties: {
          'templateOptions.placeholder': **i18nService.getTranslation('Company Name')**
        }
      }].

Error : SyntaxError: Unexpected identifier

I have included i18Services in my component.

I also tried following tried.

let formField = [{
      className: 'row',
      fieldGroup: [{
        className: 'col-sm-4 col-xs-12',
        key: 'name',
        type: 'input',
        templateOptions: {
            label: 'Company Name',
            placeholder: i18nService.getTranslation('Company Name'),
            addonRight: {
             class: 'fa fa-user',
             onClick: (to, fieldType, $event) => console.log(to, fieldType, $event),
          },
        },
        validators: {
          validation: Validators.compose([Validators.required])
        },
        expressionProperties: {
          'templateOptions.placeholder': **"'Compnay Name' | i18n"**
        }
      }].
Error  ;ReferenceError: i18n is not defined

I have included i18nModule in my module.

**Comment by mohammedzamakhan** [comment]
This `i18nService.getTranslation('Company Name')` should have worked. I don't think its an issue with this repo, please ask i18nService to support it. Thanks
