### ISSUE TITLE
Input don't reflect changes in two-way data binding on model update

### ISSUE THREAD

**Issue by diegochavez** [formly-js/ng-formly#493]
**I'm submitting a bug on input don't reflect model changes.
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I'm trying to set the value to a model attribute in this example, using the method to add value to a key directly but the input is not showing the model change

**Expected behavior**
In angular formly previous versions, we have too-way data binding by default right? On angular 4 we need something else to have two-way data binding on input fields?

**Minimal reproduction of the problem with instructions**

Enter to this plunker and click on button Add Email the model value updates but the input isn't reflecting changes.
https://plnkr.co/edit/ejreOE0bQkvnH5vCtvMS?p=preview

**Comment by aitboudad** [comment]
To change the model value you can use `this.form.get('email').setValue("example@example.com");` for example or use the formControl defined in the fields config.

https://plnkr.co/edit/6w58ZMm4BNNZE90Jo7ZN?p=preview

**Comment by diegochavez** [comment]
Awesome! thanks, @aitboudad I thought was this model related to input values, so we need to refer to the form to update input value and model.

**Comment by stubbst** [comment]
Hi. Thanks, I had the same problem :).

I was however wondering why not support the 2-way binding to have the same behaviour as in ng-formly for angularJs.

**Comment by aitboudad** [comment]
@stubbst AFAIK the 2-way binding is not possible with reactive forms provided by angular

**Comment by stubbst** [comment]
@aitboudad right, thanks :)
