### ISSUE TITLE
override wrappers

### ISSUE THREAD

**Issue by yoavdamri** [formly-js/ng-formly#494]
I'm submitting a 
```
[ X ] support request
```

**What is the motivation / use case for changing the behavior?**
The motivation is to add some elements, changing the position of elements

**Please tell us about your environment:**
i am using a fork of the Formly Introductory Example

i need to show the description and the validation errors on a tooltip by hover an icon.
i thought the way to do it is to override the "formly-wrapper-description" and "formly-wrapper-validation-messages" maybe some other wrappers.

please advise, thanks.

**Comment by mohammedzamakhan** [comment]
You can always do that using this library. FormlyConfig Service can be injected, and you can use setWrapper method and override it

**Comment by moplin** [comment]
Please, some help, I can't find the way to replace/override the wrapper. really need this to be able to use floating attribute on ionic. 
If I don't do this, then, my problem is that my component gest wrapped twice.

May be an example or the documentation for this.

Thanks

**Comment by aitboudad** [comment]
@moplin just define the wrapper you want to override through `forRoot` config:
```ts
 FormlyModule.forRoot({
   wrappers: [
     { name: 'form-field', component: CustomWrapperComponent },
   ],
 }),
```
https://formly-js.github.io/ngx-formly/guide/custom-formly-wrapper

**Comment by moplin** [comment]
Thanks my friend for the fast answer.
I already did exactly that, but formly is using my wrapper over the main wrapper.
It's doing something like i.e.
<custom-wrapper>
<main-wrapper>
<field/>
</main-wrapper>
</custom-wrapper>

I would need to do something like
<custom-wrapper>
<field/>
</custom-wrapper>

some code
my custom-wrapper
@Component({
  selector: 'formly-wrapper-mm-form-field',
  template: `
     ++ <ng-template #fieldComponent></ng-template> ++
`,
})

but is showing 

[image](https://firebasestorage.googleapis.com/v0/b/etg-prod.appspot.com/o/Image_06122018_001.png?alt=media&token=191af6be-0b6f-4d6a-81aa-c1726826d24d)

**Comment by moplin** [comment]
Sorry, no luck. It is still applying the main ionic wrapper at the end.

**Comment by aitboudad** [comment]
then fill a new issue with a reproduction example :).

if you're looking for a floating label use `labelPosition` https://github.com/formly-js/ngx-formly/issues/1263#issuecomment-434982843

**Comment by moplin** [comment]
Thanks, do this work with ionic 3? I thought that this was only ionic 4 compatible.

**Comment by aitboudad** [comment]
I think only available in ionic 4.
