### ISSUE TITLE
Repeated section renders same value when edit

### ISSUE THREAD

**Issue by arunnayak** [formly-js/ng-formly#495]
Hello,

In this example https://ng2.angular-formly.com/guides/introductory-example.html
when I try to edit investment name, it changes the value to the edited one in all investments.
e.g.

go to the introductory example and edit investment name to "test"

before edit the json look like this:
"investments": [
    {
      "investmentName": "Formly",
      "investmentDate": "02-11-2001",
      "stockIdentifier": "FO"
    },
    {
      "investmentName": "Formly Website",
      "investmentDate": "02-11-2001",
      "stockIdentifier": "FW"
    }
  ]

after the edit :

"investments": [
    {
      "investmentName": "test",
      "investmentDate": "02-11-2001",
      "stockIdentifier": "FO"
    },
    {
      "investmentName": "test",
      "investmentDate": "02-11-2001",
      "stockIdentifier": "FW"
    }
  ]

as you see in the json the values are same for both investment.
and this is happening on the example itslef.

Let me know if you have any questions.

**Comment by andriy101** [comment]
please check this closed issue https://github.com/formly-js/ng-formly/issues/452, it might help

**Comment by arunnayak** [comment]
that worked like a champ!! Thanking you!!!
