### ISSUE TITLE
Disable Chrome Autocomplete Globally

### ISSUE THREAD

**Issue by marcodafonseca** [formly-js/ng-formly#496]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request
```

**Current behavior**
Chrome can auto-populate forms

**Expected behavior**
Chrome not being able to do this like in Formly for Angular 1

**Minimal reproduction of the problem with instructions**
Step 1: Build a form
Step 2: Submit the form
Step 3: Try submit it again. Chrome should auto-complete it or at least try to

**What is the motivation / use case for changing the behavior?**
My site I am working on is full of QA type forms, so the user must always enter in the detail manually in full

**Please tell us about your environment:**
Windows\IIS

* **Angular version:** 2.0.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   6.9.1

UPDATE
- Removed links to other issues in repo. Didn't realize the # created the allowance for creating those links

**Comment by aitboudad** [comment]
hi, can you point us to an example ?

**Comment by WuglyakBolgoink** [comment]
@aitboudad and what was the answer to this question?

**Comment by aitboudad** [comment]
@WuglyakBolgoink you may use a custom extension (landed in V5) which allows you to customize fields during build process, see the following example https://stackblitz.com/edit/angular-gqidyp-tco1fc
