### ISSUE TITLE
Labels do not show for custom types

### ISSUE THREAD

**Issue by travis1234** [formly-js/ng-formly#502]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Labels are not shown for custom types.

**Expected behavior**
Labels are defined in the form definition so they should be rendered for custom types.

**Minimal reproduction of the problem with instructions**
Problem can be seen in the current official examples.
e.g: https://plnkr.co/edit/b0TOg5IYPCDp6fZFyNes?p=info

**What is the motivation / use case for changing the behavior?**
Custom Types are pretty useless without input labels

**Please tell us about your environment:**

* **Angular version:** 4.3.6

* **Browser:** all

 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** `node --version` =  v7.4.0

**Comment by aitboudad** [comment]
fixed and published under `1.0.0-rc.11`
