### ISSUE TITLE
Disabled option not applying for multicheckbox type

### ISSUE THREAD

**Issue by travis1234** [formly-js/ng-formly#505]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

`disabled: true,`  inside `templateOptions` seems to have no affect on multicheckbox type

**Expected behavior**

`disabled: true,` inside `templateOptions` should disable all checkboxes in a multicheckbox type.

Suggest also that that `disabled: true,` inside `options` could disable a single checkbox in a multicheckbox type.

This was brought up in Issue #75 but I don't think anything was changed for multicheckboxs.

**Minimal reproduction of the problem with instructions**

Problem can be seen here:
https://plnkr.co/edit/gmFFfcWePvCa1NmxyaGi?p=preview

**What is the motivation / use case for changing the behavior?**

This change will support advanced business logic in forms. 

**Please tell us about your environment:**

    Angular version: 4.3.6

    Browser: all

    Language: TypeScript 2.4.2

    Node (for AoT issues): node --version = v7.4.0

**Comment by aitboudad** [comment]
fixed by #506 and published under `1.0.0-rc.12`
