### ISSUE TITLE
Cascading Drop Down using ng2-formly in Angular 2

### ISSUE THREAD

**Issue by arielchawla** [formly-js/ng-formly#513]
I am using ng2-formly in Angular 2. I want to make a simple demo for Cascading Drop Down. Please let me know what formly Json format i can use to make it working. Please check the following demo i created on plunker, here is the link. 

"https://plnkr.co/edit/x0aCCnrpMSfGc8ctE06i?p=preview"

Thanks in Advance

**Comment by mohammedzamakhan** [comment]
I didn't create the example to your requirements, but this should help you in solving it

https://plnkr.co/edit/eUpBPAZofIGuFlpEHraW?p=preview

**Comment by arielchawla** [comment]
Thanks for your feedback.
I have checked for your plnkr link, but in my case the formly json come from backend api. Is there any ng-formly property like "expressionProperties", by using that i can bind the filtered data with second drop down. Or on change event i can set the options for second drop down dynamically as the formly json can have multiple fields or different positions.

I have also checked for below link but it's not working for me:
"http://angular-formly.com/#!/example/other/filter-select"

Please let me know if there have any solution for this.

Thanks
