### ISSUE TITLE
Unwanted paddings if fields are put in a row

### ISSUE THREAD

**Issue by swirlsky** [formly-js/ng-formly#515]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior**
"row"s get unwanted left and right paddings. (The purple area shows an unwanted left padding.)

![formly](https://user-images.githubusercontent.com/27681171/30508718-92b77876-9a9d-11e7-80ea-9b0237def1f5.png)

**Expected behavior**
There should be no paddings on the left and right sides of a "row".

**Minimal reproduction of the problem with instructions**
See https://ng2.angular-formly.com/guides/advanced-layout.html .

**What is the motivation / use case for changing the behavior?**
Better, more consistent look, form fields would be aligned more nicely. And it is unwanted because: First I thought this behavior might be an inevitable side-effect of Bootstrap's grid system, but then I tried this code and it doesn't cause these paddings:

```
<div class="row">
  <div class="col-xs-6">
    <div class="form-group">
      <label for="textbox1">Text box 1</label>
      <input type="text" class="form-control" id="textbox1" name="textbox1">
    </div>
  </div>
  <div class="col-xs-6">
    <div class="form-group">
      <label for="textbox2">Text box 2</label>
      <input type="text" class="form-control" id="textbox2" name="textbox2">
    </div>
  </div>
</div>
```

* **Browser:**
Firefox 55.0.2

**Comment by aitboudad** [comment]
`className` used in the example refer to the root element `form-field` and not to the `form-field` created by `fieldGroup` to solve that issue we introduced `fieldGroupClassName`

```html
<formly-field [ngClass]="field.className">
  <formly-group>
     <formly-field [ngClass]="field.fieldGroupClassName"></formly-field>
  </formly-group>
</formly-field>
```
see a working example: https://stackblitz.com/edit/angular-5ioeet

Note: if you still using the alpha version of bootstrap add:
```css
formly-form { display: block; }
```
into you style (related to https://github.com/angular/angular/issues/5960).

**Comment by SpiraMira** [comment]
Excellent - That works! Thanks again.
