### ISSUE TITLE
labels should be appended with an asterisk symbol when required

### ISSUE THREAD

**Issue by travis1234** [formly-js/ng-formly#517]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

Input labels with the required attribute set do not append with the asterisk symbol ( * ) 

**Expected behavior**
Input labels should be appended with an asterisk symbol ( * ) if the required attribute is set. 

**Minimal reproduction of the problem with instructions**

Working in formly-js:
http://jsbin.com/kunaho/47/edit?html,css,js,output

Not working in ng-formly
https://plnkr.co/edit/x4ev1QmJ8gm7USGsJdMQ?p=preview

**What is the motivation / use case for changing the behavior?**

Although you *could* manually append each label you know is required this adds a lot of overhead and is not a good solution for dynamic forms. I believe this is also default functionality in formly-js.

**Please tell us about your environment:**

Angular version: 4.3.6
Browser: all
Language: TypeScript 2.4.2
Node (for AoT issues): node --version = v7.4.0

**Comment by aitboudad** [comment]
fixed on master, you have to upgrade to the new package name `@ngx-formly/bootstrap`:

#### Before:
```ts
import { FormlyModule, FormlyBootstrapModule } from 'ng-formly';
```
#### After:
```ts
import { FormlyModule } from '@ngx-formly/core';
import { FormlyBootstrapModule } from '@ngx-formly/bootstrap';
```

**Comment by IustiNN** [comment]
I understand the feature. But there is a way to remove the asterisk symbol ( * ) ? I have a form where all inputs are required, so it's a bit redundant to show a star every each label.

**Comment by aitboudad** [comment]
@IustiNN there is no way but we can introduce an option `hideRequiredMarker` to remove the asterisk symbol similar to angular material does for `form-field`, can you fill an issue ? I'll look into it later.

**Comment by IustiNN** [comment]
Sure! Thanks a lot.
