### ISSUE TITLE
Wizard Directive would be very helpful

### ISSUE THREAD

**Issue by Byloor** [formly-js/ng-formly#519]
Excellent work!  but I need also Wizard Forms and it would be awesome if a sample or even better an extension to allow Angular-Formly to create Wizards.

The wizard should have
validation per step, i.o. disable next button / showing message if fields are not completed.
hiding/showing steps based on conditions with previous filled in fields (model values)
skipping steps (hided steps should be skipped anyway)
optional finish button on last step
wizard in wizard (on a step showing another wizard)
Different layouts (tab, steps, pills, progress bar, collapsable sections, etc.
JSON configurable
there most likely more options to add.

**Comment by mohammedzamakhan** [comment]
Creating new types is easy, I think since the wizard would be different for different projects, the developers should create it for it.

Would not be a good idea to create here

**Comment by aitboudad** [comment]
see the example https://stackblitz.com/edit/angular-dyfauh, it will be part of doc examples.
