### ISSUE TITLE
repeatSection binding controls to the same model value

### ISSUE THREAD

**Issue by stabac** [formly-js/ng-formly#530]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Controls in repeatSection are being bound to the same model(same array item). It can be seen in the current demo,  typing "Test" for "Name of Investment" of the first Investment makes all Investments have the same typed value.  Might be related to this issue https://plnkr.co/edit/wfHOd0?p=preview

**Expected behavior**
Each item in repeatSection is bound to a separate array item.

**Minimal reproduction of the problem with instructions**
In the official introductory example type "Test" for "Name of Investment" of the first Investment. Now all "Name of Investment" fields have the same value "Test".

**Please tell us about your environment:**
Windows 10, Chrome, official introductory example

**Comment by aitboudad** [comment]
already fixed see https://github.com/formly-js/ng-formly/issues/452#issuecomment-310035999, doc to be updated soon

**Comment by stabac** [comment]
@aitboudad That works as expected, thanks! On a related note if form model is being loaded asynchronously, i.e. like this 

`Promise.resolve(null).then(() => { this.model = {...} })`

repeatSection is not being initialized since model is only processed in ngOnInit. Is there an easy way(event) to refresh it on model change?

**Comment by aitboudad** [comment]
@stabac declare a reset function inside `RepeatComponent` and assign it to the formField which you can re-initialize the component whenever you want.

```ts
export class RepeatComponent extends FieldType implements OnInit {
  ngOnInit() {
    ....
    this.field.reset = () => this.reset();
  }
  reset() {
     ....
  }
}
```

```ts
Promise.resolve(null).then(() => { 
  this.model = {...};
  this.field.reset();
})

```
