### ISSUE TITLE
Wrapper for input type radio

### ISSUE THREAD

**Issue by maik10** [formly-js/ng-formly#531]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

Need create a custom template for radio buttons but i not found documentation to make that.

**Expected behavior**

Insert the radios into a list and move the label before the field

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   Last Version

**Comment by aitboudad** [comment]
To create a custom type you have to create a custom compoment and register it in the config module:
 
1- create your custom component that extend `FieldType`:

```ts
import { Component } from '@angular/core';
import { FieldType } from 'ng-formly';

@Component({
  selector: 'formly-field-radio',
  template: ` .... `,
})
export class FormlyFieldRadio extends FieldType {}
```
see https://github.com/formly-js/ng-formly/blob/master/src/ui-bootstrap/src/types/radio.ts

2- register the new type in `FormlyModule`
```ts
@NgModule({
  declarations: [FormlyFieldRadio],
  imports: [
    ....
    FormlyBootstrapModule,
    FormlyModule.forRoot({ types: [
        { name: 'radio', component: FormlyFieldRadio },
    ] }),
  ],
})
export class AppModule {}
```

also check the [demo](https://github.com/formly-js/ng-formly/tree/master/demo) example  and bootstrap implementation [bootstrap](https://github.com/formly-js/ng-formly/tree/master/src/ui-bootstrap/src) for more examples.
