### ISSUE TITLE
2 way binding doesn't work for model loaded asynchronously

### ISSUE THREAD

**Issue by stabac** [formly-js/ng-formly#535]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
If formFields are defined instantly and formModel is loaded asynchronously 2 way binding is not working. Meaning UI shows the model values, but changing any of the inputs' values doesn't update the model.

```
export class App {
    formFields = { ... }
    
    ngOnInit() {
        Promise.resolve(null).then(() => {
            this.formModel = { ... }
        }
    }
}
```

Assigning formFields after the model fixes the issue.

```
export class App {
    _formFields = { ... };
    formFields;
    
    ngOnInit() {
        Promise.resolve(null).then(() => {
            this.formModel = { ... }
            this.formFields = this._formFields;
        }
    }
}
```

**Comment by stabac** [comment]
@aitboudad I noticed you used ngx-formly where I was using ng-formly. Not sure if that makes a difference or there is something in my app that breaks it. Could you explain if I should be using ngx and how to install it?

**Comment by aitboudad** [comment]
it's the same with `ng-formly`, to use the `@ngx-formly` just ensure you don't still using any deprecated methods see:
https://github.com/formly-js/ng-formly/issues/514#issuecomment-335165220

**Comment by stabac** [comment]
I guess the problem is in my code then. Thanks for looking into it!
