### ISSUE TITLE
can we make a property ,field or fieldGroup depending upon the sibling field value

### ISSUE THREAD

**Issue by HazizKhan** [formly-js/ng-formly#551]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[ ] feature request
[x] support request => search github for a similar issue or PR before submitting
```

**Current behavior**

Currently I have formlyFieldConfig like this: 
```
{
      key: 'my_parent_key',
      fieldGroup: [   /* suppose this fieldGroup as "field_group_one" */
        {
          key: 'my_select', /* suppose this field as "my_select"  */
          type: 'select',
          templateOptions: {
            options: [
              {
                label: 'Exact',
                value: 'exact',
              },
              {
                label: 'Range',
                value: 'range',
                selected: true
              }
            ]
          }
        }
      ]
    }
```

**Expected behavior**

my concern is if i select "Exact" in my_select then i have to push a "field" in field_group_one. i.e
```
{
  key: 'value',
  type: 'input',
  templateOptions: {
    type: 'text',
    placeholder: 'Value'
  }
}
```
and if i select range then i have to push a "fieldGroup" along with "fields" in field_group_one. i.e
```
{
  key: 'value',
  fieldGroup: [
   {
     key: 'min',
     type: 'input'
     templateOptions: {
       type: 'text',
       placeholder: 'Min'
     }
   },
   {
     key: 'max',
     type: 'input'
     templateOptions: {
       type: 'text',
       placeholder: 'Max'
     }
   }
  ]
}
```

**Comment by aitboudad** [comment]
use `hideExpression` property: see https://stackblitz.com/edit/angular-ghrcbj?file=app%2Fapp.component.ts

**Comment by aitboudad** [comment]
Note: `hideExpression` can also be a function:
```patch
-- hideExpression: 'model.my_select !== "exact"',
++ hideExpression: (model) => model.my_select !== "exact",
```

**Comment by HazizKhan** [comment]
Thanks for replying. There is a problem. when i select "exact" and and type a value in value field and then select range (without clearing the value field) and then type value on min or max field then it is throwing error: `ERROR TypeError: Cannot create property 'min' on string '1'`
![image](https://user-images.githubusercontent.com/13147389/32497608-e61dd6d4-c3ee-11e7-9301-2ac4db15e299.png)

**Comment by aitboudad** [comment]
@HazizKhan fixed by #552, you need to update into `2.0.0-beta.3`

**Comment by HazizKhan** [comment]
Hi, @aitboudad I think when toggling hide the field model should be reset to null or empty string because if i select "exact" and type "asd" in "value" field and i select "range" and then type "xyz" in "value.min" field then again i select "exact" now i am seeing "asd" in input but my model looks like this:
```
value: { min: 'xyz'}
```

**Comment by aitboudad** [comment]
@HazizKhan I updated the [example](https://stackblitz.com/edit/angular-ghrcbj?file=app%2Fapp.component.ts)  by setting value to null whenever field `hidden` is changed
```ts
      lifecycle: {
        onInit: () => {
          this.options.fieldChanges.subscribe(({field, type, value}) => {
            if (type === 'hidden' && field.formControl) {
              field.formControl.setValue(null);
            }
          });
        },
      },
```

**Comment by HazizKhan** [comment]
@aitboudad Thanks :)
