### ISSUE TITLE
Multiselect option

### ISSUE THREAD

**Issue by nikul1993** [formly-js/ng-formly#554]
Hello Team,

How can I integrate multiselect select box like that

http://silviomoreto.github.io/bootstrap-select/examples/#multiple-select-boxes

**Comment by aitboudad** [comment]
see the example https://stackblitz.com/edit/angular-ntysej 
Note: I used https://github.com/ng-select/ng-select

**Comment by nikul1993** [comment]
@aitboudad 

Thanks for your quick response, but how can I use third party plugin in our ng-formly.

**Comment by aitboudad** [comment]
@nikul1993 not sure I understand your question, just follow the example and you'll get what you want.

**Comment by nikul1993** [comment]
@aitboudad 

Thanks for the example. I am using version **1.0.0-rc.10** of ng-formly.
And the example that you have given is **2.0.0-beta.2**.
I can not use that version. 
Is the example given by you is compatible with the version I am using?
Thank you

**Comment by aitboudad** [comment]
@nikul1993 you easily upgrade into the new version see https://github.com/formly-js/ng-formly/issues/501#issuecomment-337271517 and if you're not ready yet to upgrade just replace `@ngx-formly/core` by `ng-formly`

**Comment by nikul1993** [comment]
@aitboudad 

Thank you very much for your support.. :)

**Comment by davidoween** [comment]
I have solved it. I needed to add the formControl

**Comment by james-poulose** [comment]
> see the example https://stackblitz.com/edit/angular-ntysej
> Note: I used https://github.com/ng-select/ng-select

@aitboudad I followed the example you provided in the above link and everything works great! Rest of my `ng-formly` fields show an asterisk for required fields except this one (formly with ng-select). Any thoughts on that?
Thanks,
James

**Comment by aitboudad** [comment]
@james-poulose you have to use `form-field` as a wrapper:

```patch
FormlyModule.forRoot({
  types: [
    { 
      name: 'ng-select',
      component: FormlyFieldNgSelect,
+     wrappers: ['form-field'],
    }
  ]
}),
```

**Comment by james-poulose** [comment]
> @james-poulose you have to use `form-field` as a wrapper:
> 
> ```diff
> FormlyModule.forRoot({
>   types: [
>     { 
>       name: 'ng-select',
>       component: FormlyFieldNgSelect,
> +     wrappers: ['form-field'],
>     }
>   ]
> }),
> ```
@aitboudad That did it - almost. I now see an an additional horizontal line below the multi-select control. I have a stackblitz to demo that 
https://stackblitz.com/edit/angular-fc8pvb
At this point i am not sure if this is an `ng-select` issue or an `ngx-formly` matter. If this is an `ng-select` one, i will post it on their forums. it would be great if you can let me know your thoughts
Thanks,
James

**Comment by james-poulose** [comment]
> you've to adjust their style to make it compatible with material2 form-field see https://stackblitz.com/edit/angular-ngx-formly-ngselect-material-2bj3sf?file=app%2Ftypes%2Fng-select.type.component.scss

@aitboudad It worked like a charm!! Really appreciate your work.
Thanks again,
James
