### ISSUE TITLE
Inject formly-form content inside a wrapper

### ISSUE THREAD

**Issue by jogelin** [formly-js/ng-formly#555]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[X] support request
```

**Current behavior**
When I open the code (`formly.form.ts`), I see that the content is display below the wrapper:
```
    <formly-field *ngFor="let field of fields"
      [model]="fieldModel(field)" [form]="form"
      [field]="field" (modelChange)="changeModel($event)"
      [ngClass]="field.className"
      [options]="options">
    </formly-field>
    <ng-content></ng-content>
```

**Expected behavior**
I there a way to inject this content inside the wrapper ?

**Minimal reproduction of the problem with instructions**
To be more clear, I created a card wrapper (like tour panel wrapper in your demo) but I would like to display the submit button in the `mat-card-actions`:

My Wrapper:
```
@Component({
  selector: 'app-card-wrapper',
  template: `
    <mat-card>
      <mat-card-content>
        <ng-container #fieldComponent></ng-container>
      </mat-card-content>
      <mat-card-actions align="end">
        <!-- DISPLAY THE BUTTON HERE -->
      </mat-card-actions>
    </mat-card>
  `,
})
export class FormlyCardWrapperComponent extends FieldWrapper {
  @ViewChild('fieldComponent', { read: ViewContainerRef }) fieldComponent: ViewContainerRef;
}
```

My Form:
```
    <form class="formly" role="form" novalidate [formGroup]="form" (ngSubmit)="submit(model)">
      <formly-form [model]="model" [fields]="fields">
          <button type="submit" class="btn btn-default">Submit</button>
      </formly-form>
    </form>
```

* **Angular version:** 5.0.0
* **Formly:** 2.0.0-beta.2

**Comment by aitboudad** [comment]
see the example: https://stackblitz.com/edit/angular-y1lhbz
I used [cdk portal](https://material.angular.io/cdk/portal/overview) to achieve your use-case

**Comment by jogelin** [comment]
Thx ! I should start to learn this new cdk stuff ;)
