### ISSUE TITLE
Material: display input length as hint

### ISSUE THREAD

**Issue by jogelin** [formly-js/ng-formly#556]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[X] support request
```

**Current behavior**
Indication about input length does not exist

**Expected behavior**
Usually, when we specify a maxLength for an input, we display the length and the maxLength as a hint below the input:
```
<form class="example-form">

  <mat-form-field class="example-full-width">
    <input matInput #message maxlength="256" placeholder="Message">
    <mat-hint align="start"><strong>Don't disclose personal info</strong> </mat-hint>
    <mat-hint align="end">{{message.value.length}} / 256</mat-hint>
  </mat-form-field>
  
</form>
```

Is it working with your material implemention of the input ?

**Comment by aitboudad** [comment]
right now the material implementation is very light we planned to provide more functionalities once material2 solve some several issues see my comment https://github.com/formly-js/ng-formly/issues/335#issuecomment-338225216 for more details.
In the meantime you can create you own input type.

**Comment by jogelin** [comment]
Ok, thx for your answer !

I'll create my own component so

**Comment by arnaudval** [comment]
Good afternoon, 
do you have any example on how to create such a custom field or wrapper ?

thanks in advance
Arnaud

**Comment by aitboudad** [comment]
here is a simple example for displaying input length as hint: https://stackblitz.com/edit/angular-bvfka4

**Comment by aitboudad** [comment]
and for custom wrapper, you may check the doc https://ngx-formly.github.io/ngx-formly/guide/custom-formly-wrapper

**Comment by arnaudval** [comment]
Hi Abdellatif,

many thanks for your (very) fast answer. I was looking for a hint aligned on left side. this is for displaying units (€,$, m²,...) do you have any advice on it ?

To present myself, i'm 43 years old guy, with 30 years of IT know-how and 21 years of actual "professional" IT experience, mainly in Java/C#.

I'm always looking for new things so I started to use Angular 3 years ago and I'm very keen of using existing good frameworks (like Formly is). I must admit I'm still a beginner in deep details of Ng components/packages but i'll be pleased to help in any way

Kind regards
Arnaud


________________________________
De : Abdellatif Ait boudad <notifications@github.com>
Envoyé : jeudi 25 avril 2019 19:57
À : ngx-formly/ngx-formly
Cc : arnaudval; Comment
Objet : Re: [ngx-formly/ngx-formly] Material: display input length as hint (#556)


here is a simple example for displaying input length as hint: https://stackblitz.com/edit/angular-bvfka4

**Comment by arnaudval** [comment]
aligned on right side, sorry

________________________________
De : arnaud vallette <arnaud.vallette@outlook.com>
Envoyé : jeudi 25 avril 2019 22:11
À : ngx-formly/ngx-formly
Objet : RE: [ngx-formly/ngx-formly] Material: display input length as hint (#556)

Hi Abdellatif,

many thanks for your (very) fast answer. I was looking for a hint aligned on left side. this is for displaying units (€,$, m²,...) do you have any advice on it ?

To present myself, i'm 43 years old guy, with 30 years of IT know-how and 21 years of actual "professional" IT experience, mainly in Java/C#.

I'm always looking for new things so I started to use Angular 3 years ago and I'm very keen of using existing good frameworks (like Formly is). I must admit I'm still a beginner in deep details of Ng components/packages but i'll be pleased to help in any way

Kind regards
Arnaud


________________________________
De : Abdellatif Ait boudad <notifications@github.com>
Envoyé : jeudi 25 avril 2019 19:57
À : ngx-formly/ngx-formly
Cc : arnaudval; Comment
Objet : Re: [ngx-formly/ngx-formly] Material: display input length as hint (#556)


here is a simple example for displaying input length as hint: https://stackblitz.com/edit/angular-bvfka4

**Comment by aitboudad** [comment]
> To present myself, i'm 43 years old guy, with 30 years of IT know-how and 21 years of actual "professional" IT experience, mainly in Java/C#.

Welcome to the new world :smiley:

> I was looking for a hint aligned on left side. this is for displaying units (€,$, m²,...) do you have any advice on it ?

:thinking: I think you're looking for https://ngx-formly.github.io/ngx-formly/examples/other/material-prefix-suffix
