### ISSUE TITLE
Making a fieldGroup collapsible

### ISSUE THREAD

**Issue by MassiveHiggsField** [formly-js/ng-formly#565]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```
I'm using this to make a div collapsible in my app:

    <a (click)="environment.showDetails = !environment.showDetails">
        <span class="pull-left">show details</span>
        <span class="pull-right"><em class="fa fa-chevron-circle-right"></em></span>
    </a>
    <div [collapse]="!environment.showDetails">...</div>

How can i combine this with a fieldgroup to make it collapsible?

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-pnmmlb
