### ISSUE TITLE
Show messages errors after of submiter

### ISSUE THREAD

**Issue by davidoween** [formly-js/ng-formly#566]
Hello I want to show the error messages when the user clicks on the upload form, not only when the user touches the field. Thank you

**Comment by aitboudad** [comment]
Hi @davidoween, I think this should be the default behavior right now you have to pass an extra option in the config to make it work (see the working example https://stackblitz.com/edit/angular-mqkvay):

1. define custom `showError` function
```ts
export function showErrorOption(field) {
  return (field.formState.submitted || field.formControl.touched || (field.field.validation && field.field.validation.show)) && !field.formControl.valid;
}

@NgModule({
  imports: [ 
    ...,
    FormlyModule.forRoot({
      extras: { showError: showErrorOption },
    }),
  ],
})
```
2. pass `options` into your `formly-form` and change `formState.submitted` property to `true` when you submit the form
```ts
@Component({
  selector: 'my-app',
  template: `
      <formly-form 
        ...
        [options]="options">
      </formly-form>
  `,
})
export class AppComponent {
  options: { formState: { submitted: false } },

  submit(user) {
    this.options.formState.submitted = true;
   ...
  }
```

**Comment by aitboudad** [comment]
since `2.0.0-beta.5` errors are shown if form is submitted
