### ISSUE TITLE
where to add fields dynamically to formly

### ISSUE THREAD

**Issue by davidoween** [formly-js/ng-formly#569]
Hello, where to add fields dynamically to formly?

I just add an element to the array this.form.fields but it's not enough. This the code:

`<form [formGroup]="form.formGroup" (ngSubmit)="submit(userModel)">
  <formly-form [form]="form.formGroup" [model]="form.model" [fields]="form.fields" [options]="form.options">
  </formly-form>
  <button type="submit">Submit</button>
</form>`

**Comment by aitboudad** [comment]
@davidoween you should pass a new ref to the field to take account of your changes

**Comment by IustiNN** [comment]
@aitboudad what do you mean with that?

**Comment by aitboudad** [comment]
@IustiNN I mean:
```ts
form.fields = [ ...form.fields, { key: 'title', type: 'input' }];
// instead of
form.fields.push({ key: 'title', type: 'input' });
```

**Comment by IustiNN** [comment]
@aitboudad Thank you very much!

**Comment by chaosLegacy** [comment]
Hi sir I'm also looking for a way to add input dynamically to my form so what i have here for testing is this `
import {FormArray, FormGroup} from '@angular/forms';
import {FormlyFormOptions, FormlyFieldConfig} from '@ngx-formly/core';
import { FieldType, FormlyFormBuilder } from '@ngx-formly/core';
  form = new FormGroup({});
  fields: FormlyFieldConfig[];
  formControl: FormArray;
  model: any = {};
setTimeout(function() {
      let template = {
        key: 'myInput',
        type: 'horizontalInput',
        templateOptions: {
          type: 'text',
          label: 'My input',
          placeholder: 'My input',
          required: true,
        }
      };
      this.fields.push(template);
      this.builder.buildForm(this.form, this.fields[0], this.model[0], this.options);
      this.formControl.push(this.form);
    }.bind(this), 5000);` 
as a result my new input got created but without a label nor validation and not recognized by model what i want is the possibility to inject the new input in the position i pass on a parametre
is there a way i can do that

**Comment by aitboudad** [comment]
not sure what do you want to achieve if you're looking for an easy way to manage repeating fields please check the following example: https://formly-js.github.io/ngx-formly/examples/advanced/repeating-section
