### ISSUE TITLE
Introductory Examples only allow to select 1 button

### ISSUE THREAD

**Issue by DMarinsa** [formly-js/ng-formly#571]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
Radio button in Introductory Example only Allow to select 1 element

**Expected behavior**
There are 2 different objects of the same type, radio button in this case, you have 2 elements (Title1 & Title2) with 2 different options each one (mr. & mrs) so  I should be able to select 2 differents options.

**What is the motivation / use case for changing the behavior?**

I'm starting to use ng-formly and I'd like to learn how to develop correctly with it.
**Please tell us about your environment:**

Win 10 , VSCode
* **Angular version:** 5.0.1

IT is
* **Browser:** [| Chrome XX | Firefox XX | ]

 Chrome, Firefox
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by aitboudad** [comment]
the demo app is based on an old version, I tested with the latest one and it seems working as expected, the demo will be updated soon I just need to find some time see https://github.com/formly-js/ng-formly/issues/543
