### ISSUE TITLE
hideExpression with select inputs

### ISSUE THREAD

**Issue by travis1234** [formly-js/ng-formly#575]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```

**Minimal reproduction of the problem with instructions**

I'm trying to figure out how to conditionally show an input after I pick a value from a select or multi-select type input. 

For example in the case of a multi-select I want to show a hidden field whenever option 4 is selected:

If Option 4 is selected, then show hidden input.
If Option 4 AND Option 1 is selected, then show hidden input.
If Option 1 is selected, then don't show hidden input.

I've setup a quick demo but it's not behaving as excepted. Any help is much appreciated!

https://angular-bavx7u.stackblitz.io

* **Angular version:** 2.0.X

* **Browser:** [ all ]

 
* **Language:** [ all ]

* **Node (for AoT issues):** `node --version` =  [ all ]

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-ntysej?file=app%2Fapp.component.ts
