### ISSUE TITLE
Forked project, cloned, ran npm install => error

### ISSUE THREAD

**Issue by razorphish** [formly-js/ng-formly#578]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
On Npm Install getting a npm run build error

**Expected behavior**
Modules would be installed without error

**Minimal reproduction of the problem with instructions**
Fork Ng-formly
Clone
[npm-debug.log](https://github.com/formly-js/ng-formly/files/1512606/npm-debug.log)

Run 'npm install'

**What is the motivation / use case for changing the behavior?**
Get it to build correctly

**Please tell us about your environment:**
Attempted on following platforms:
Windows 10
Linux 

* **Angular version:** 2.0.X
Yes

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   6.11.0

**Comment by aitboudad** [comment]
we use yarn can you try with `yarn install` instead after removing `node_modules`

**Comment by razorphish** [comment]
Yep, thats it.  Thank you
