### ISSUE TITLE
Change dynamically the fields and the model of a formly form

### ISSUE THREAD

**Issue by Pat-Lovelace** [formly-js/ng-formly#579]
**I'm submitting a ...**  (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request

**Minimal reproduction of the problem with instructions**

Hi,
I'm trying to change dynamically the fields and the model of a formly form. I execute the following code to update these attributes: (The parent of this component updates the formly-form  of his child component)

Child component:
HTML:
  ```
<form class="formly" role="form" novalidate [formGroup]="form">
    <formly-form [model]="model" [fields]="fields" [form]="form" [options]="options">
    </formly-form>
  </form>
```

TYPESCRIPT:

  ```
form = new FormGroup({}); 
  fields = [];
  model = {};
  options: FormlyFormOptions = {};

constructor(private builder: FormlyFormBuilder ) { }

public updateForm(){  
    this.form = new FormGroup({});
    this.fields = /*I get rightly the new fields*/;
    this.model = /* I get rightly the new model */;
    this.builder.buildForm(this.form, this.fields, this.model, this.options);
     ...
  }
```

Although the fields change rightly, the displayed model matches the previous input model, but if I show the model separately (like {{ model | json }}), the formly-form shows the right model.  

To exemplify:
My "formly-fields" is only an **input text** "name" and my "formly-model" is "name":"John Doe".
The field "name" displays "John Doe". 

If I change "formly-fields" to an **input text** "name" and an **input text** "email", and I change my "formly-model" to "name": "Mary Doe" and  "email":"mary@email.com"...
The field "name" display "John Doe" and the field "email" display "mary@email.com".

I wanna know how "reset" the "formly-model"... I'm not sure if it is related to the "initialValue"...

I appreciate any help that you can provide, thank you. 

**Please tell us about your environment:**
Win 10, VSCode 1.18.1 

* **Angular version:** 5.0.0

* **Browser:** [Firefox 57.0 ]
 
* **Language:** [ TypeScript ]

**Comment by aitboudad** [comment]
hi, can you replicate your example using https://stackblitz.com/edit/angular-9wekfg

**Comment by Pat-Lovelace** [comment]
Thanks, I replicate my example [https://stackblitz.com/edit/angular-nxpe8x](url), but here works rightly... 
I don't now why that does not work on my code... is there a better way to change fields and model of a formly form?

**Comment by aitboudad** [comment]
unstead of changing the fields why not just using `hideExpression`, see https://stackblitz.com/edit/angular-a7ha4x
